#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Contexto/Index.cshtml")]
    public partial class _Views_Contexto_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Contexto_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Contexto\Index.cshtml"
  
    string serverAPI = System.Web.Configuration.WebConfigurationManager.AppSettings["Address_LVSA.Security.Service"];
    string serverCDN = System.Web.Configuration.WebConfigurationManager.AppSettings["Address_LVSA.CDN.Presentation"];

    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewBag.Title = "Escolha de contexto";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Contexto\Index.cshtml"
 using (Html.BeginForm("Index", "Contexto", FormMethod.Post, new { @id = "Contexto" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"lc-block toggled\"");

WriteLiteral(" id=\"l-login\"");

WriteLiteral(">\r\n        <p");

WriteLiteral(" class=\"text-left\"");

WriteLiteral(">Você tem acesso a mais de um filial, selecione o contexto para começarmos.</p>\r\n" +
"\r\n        <div");

WriteLiteral(" class=\"input-group m-b-20\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-arrow-right\"");

WriteLiteral("></i></span>\r\n            <div");

WriteLiteral(" class=\"fg-line\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 16 "..\..\Views\Contexto\Index.cshtml"
           Write(Html.DropDownList("FilialId", new SelectList(ViewBag.FilialSet, "Id", "Nome", "Coligada.Nome", (short?)ViewBag.FilialId), "Selecione contexto...", new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-login btn-danger btn-float pull-right\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-arrow-forward\"");

WriteLiteral("></i></button>\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-login btn-danger btn-float pull-left\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-arrow-forward\"");

WriteLiteral("></i></button>\r\n    </div>\r\n");

            
            #line 23 "..\..\Views\Contexto\Index.cshtml"

}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"white\"");

WriteLiteral(">© ");

            
            #line 28 "..\..\Views\Contexto\Index.cshtml"
                     Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" – Housing ");

WriteLiteral("@ Leonelleo</span>\r\n</div>\r\n\r\n\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n\r\n\r\n\r\n        });\r\n\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
