#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Noticia.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Noticia/Visualizar.cshtml")]
    public partial class _Views_Noticia_Visualizar_cshtml : System.Web.Mvc.WebViewPage<LVSA.Noticia.Application.ViewModels.NoticiaViewModel>
    {
        public _Views_Noticia_Visualizar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Noticia\Visualizar.cshtml"
  
    ViewBag.Title = Model.Titulo;
    ViewBag.Description = Model.Subtitulo;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<span>\r\n    publicado por <b>");

            
            #line 9 "..\..\Views\Noticia\Visualizar.cshtml"
                Write(Model.Autor);

            
            #line default
            #line hidden
WriteLiteral("</b>\r\n</span>\r\n\r\n<span");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">");

            
            #line 12 "..\..\Views\Noticia\Visualizar.cshtml"
                    Write(Model.PublicadoEm.ToLongDateString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n<br />\r\n\r\n\r\n<br />\r\n\r\n");

            
            #line 18 "..\..\Views\Noticia\Visualizar.cshtml"
Write(new HtmlString(Model.Texto));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<br />\r\n\r\n");

            
            #line 22 "..\..\Views\Noticia\Visualizar.cshtml"
 if (Model.Tags != null)
{
    foreach (var x in Model.Tags.Split(','))
    {

            
            #line default
            #line hidden
WriteLiteral("        <label");

WriteLiteral(" class=\"label label-info\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\Noticia\Visualizar.cshtml"
                                   Write(x);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

            
            #line 27 "..\..\Views\Noticia\Visualizar.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<br />\r\n<br />\r\n\r\n<div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 36 "..\..\Views\Noticia\Visualizar.cshtml"
            
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Noticia\Visualizar.cshtml"
             if (Model.ImagemSet != null && Model.ImagemSet.Count() > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <ul");

WriteLiteral(" class=\"ace-thumbnails clearfix\"");

WriteLiteral(">\r\n");

            
            #line 39 "..\..\Views\Noticia\Visualizar.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Noticia\Visualizar.cshtml"
                      int count = 0;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 40 "..\..\Views\Noticia\Visualizar.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Noticia\Visualizar.cshtml"
                     foreach (var x in Model.ImagemSet)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li>\r\n                            <a");

WriteLiteral(" class=\"cboxElement not-show-loading\"");

WriteAttribute("href", Tuple.Create(" href=\"", 963), Tuple.Create("\"", 1027)
, Tuple.Create(Tuple.Create("", 970), Tuple.Create("data:image;base64,", 970), true)
            
            #line 43 "..\..\Views\Noticia\Visualizar.cshtml"
             , Tuple.Create(Tuple.Create("", 988), Tuple.Create<System.Object, System.Int32>(System.Convert.ToBase64String(x.Valor)
            
            #line default
            #line hidden
, 988), false)
);

WriteLiteral(" data-rel=\"colorbox\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1087), Tuple.Create("\"", 1150)
, Tuple.Create(Tuple.Create("", 1093), Tuple.Create("data:image;base64,", 1093), true)
            
            #line 44 "..\..\Views\Noticia\Visualizar.cshtml"
, Tuple.Create(Tuple.Create("", 1111), Tuple.Create<System.Object, System.Int32>(System.Convert.ToBase64String(x.Valor)
            
            #line default
            #line hidden
, 1111), false)
);

WriteLiteral(" width=\"150\"");

WriteLiteral(" height=\"150\"");

WriteLiteral(" />\r\n                                <div");

WriteLiteral(" class=\"tags\"");

WriteLiteral(">\r\n                                    <!-- #section:pages/gallery.tags -->\r\n    " +
"                                <span");

WriteLiteral(" class=\"label-holder\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"label label-info arrowed\"");

WriteLiteral(">clique para ampliar</span>\r\n                                    </span>\r\n\r\n     " +
"                               <!-- /section:pages/gallery.tags -->\r\n           " +
"                     </div>\r\n                            </a>\r\n                 " +
"       </li>\r\n");

            
            #line 55 "..\..\Views\Noticia\Visualizar.cshtml"
                        count++;
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                </ul>\r\n");

            
            #line 59 "..\..\Views\Noticia\Visualizar.cshtml"

            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
