#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Param/EditorTemplates/ParamViewModel.cshtml")]
    public partial class _Views_Param_EditorTemplates_ParamViewModel_cshtml_ : System.Web.Mvc.WebViewPage<LVSA.Base.Presentation.ViewModels.ParamViewModel>
    {
        public _Views_Param_EditorTemplates_ParamViewModel_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<label");

WriteLiteral(" class=\"block clearfix\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"block input-icon input-icon-right\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 5 "..\..\Views\Param\EditorTemplates\ParamViewModel.cshtml"
   Write(Html.HiddenFor(model => model.Key));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Param\EditorTemplates\ParamViewModel.cshtml"
        
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Param\EditorTemplates\ParamViewModel.cshtml"
         if (!Model.TSQLAtivo)
        {
            
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Param\EditorTemplates\ParamViewModel.cshtml"
       Write(Html.TextBoxFor(model => model.Value, new { @class = "form-control " + (Model.Multi ? "field-tags" : ""), @placeholder = Model.Exibicao, @data_mask = !Model.Multi && !string.IsNullOrWhiteSpace(Model.Mascara) ? "$" + Model.Mascara : "#" }));

            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Param\EditorTemplates\ParamViewModel.cshtml"
                                                                                                                                                                                                                                                           
        }
        else if (Model.Multi)
        {
            
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Param\EditorTemplates\ParamViewModel.cshtml"
       Write(Html.ListBoxFor(model => model.Values, new SelectList(Model.Collection, "Value", "Display", "GroupField", (object)Model.Values), new { @class = "form-control chosen-select", @data_placeholder = Model.Exibicao }));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Param\EditorTemplates\ParamViewModel.cshtml"
                                                                                                                                                                                                                                
        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Param\EditorTemplates\ParamViewModel.cshtml"
       Write(Html.DropDownListFor(model => model.Value, new SelectList(Model.Collection, "Value", "Display", "GroupField", (object)Model.Value), Model.Exibicao, new { @class = "form-control chosen-select" }));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Param\EditorTemplates\ParamViewModel.cshtml"
                                                                                                                                                                                                               
        }

            
            #line default
            #line hidden
WriteLiteral("        <small><span");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">");

            
            #line 18 "..\..\Views\Param\EditorTemplates\ParamViewModel.cshtml"
                                     Write(Model.Obrigatorio ? "Este parâmetro é obrigatório" : "Este parâmetro é opcional");

            
            #line default
            #line hidden
WriteLiteral(" </span></small>\r\n    </span>\r\n</label>");

        }
    }
}
#pragma warning restore 1591
