#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Profile/Index.cshtml")]
    public partial class _Views_Profile_Index_cshtml : System.Web.Mvc.WebViewPage<LVSA.Base.Presentation.ViewModels.ProfileViewModel>
    {
        public _Views_Profile_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Profile\Index.cshtml"
  
    ViewBag.Title = "Perfil";
    ViewBag.Description = "Seu perfil";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<form");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 185), Tuple.Create("\"", 224)
            
            #line 8 "..\..\Views\Profile\Index.cshtml"
, Tuple.Create(Tuple.Create("", 194), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Profile")
            
            #line default
            #line hidden
, 194), false)
);

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Views\Profile\Index.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"tabbable\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" class=\"nav nav-tabs padding-16\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(" href=\"#edit-basic\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"green ace-icon fa fa-pencil-square-o bigger-125\"");

WriteLiteral("></i>\r\n                    Informação básica\r\n                </a>\r\n            <" +
"/li>\r\n\r\n            <li>\r\n                <a");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(" href=\"#edit-settings\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"purple ace-icon fa fa-cog bigger-125\"");

WriteLiteral("></i>\r\n                    Configurações\r\n                </a>\r\n            </li>" +
"\r\n\r\n            <li>\r\n                <a");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(" href=\"#edit-password\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"blue ace-icon fa fa-key bigger-125\"");

WriteLiteral("></i>\r\n                    Senha\r\n                </a>\r\n            </li>\r\n      " +
"  </ul>\r\n\r\n        <div");

WriteLiteral(" class=\"tab-content profile-edit-tab-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"edit-basic\"");

WriteLiteral(" class=\"tab-pane in active\"");

WriteLiteral(">\r\n                <h4");

WriteLiteral(" class=\"header blue bolder smaller\"");

WriteLiteral(">Geral</h4>\r\n\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Avatar</label>\r\n                            <div");

WriteLiteral(" class=\"col-xs-12 col-sm-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 45 "..\..\Views\Profile\Index.cshtml"
                           Write(Html.TextBoxFor(model => model.File, htmlAttributes: new { @class = "form-control", @type = "file" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span");

WriteLiteral(" class=\"help-block\"");

WriteLiteral(">Atualizar a imagem de perfil</span>\r\n                            </div>\r\n       " +
"                 </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"space-4\"");

WriteLiteral("></div>\r\n\r\n                        ");

WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n            </div>\r\n\r\n   " +
"         <div");

WriteLiteral(" id=\"edit-settings\"");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"space-10\"");

WriteLiteral("></div>\r\n\r\n\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" id=\"edit-password\"");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(">\r\n                <h4");

WriteLiteral(" class=\"header blue bolder smaller\"");

WriteLiteral(">Acesso</h4>\r\n                <div");

WriteLiteral(" class=\"space-10\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(" for=\"form-field-pass1\"");

WriteLiteral(">Senha</label>\r\n\r\n                            <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 85 "..\..\Views\Profile\Index.cshtml"
                           Write(Html.PasswordFor(model => model.OldPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 86 "..\..\Views\Profile\Index.cshtml"
                           Write(Html.ValidationMessageFor(model => model.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span");

WriteLiteral(" class=\"help-block\"");

WriteLiteral(">Senha atual</span>\r\n                            </div>\r\n                        " +
"</div>\r\n\r\n\r\n                        <div");

WriteLiteral(" class=\"space-4\"");

WriteLiteral("></div>\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(" for=\"form-field-pass1\"");

WriteLiteral(">Nova senha</label>\r\n\r\n                            <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 98 "..\..\Views\Profile\Index.cshtml"
                           Write(Html.PasswordFor(model => model.NewPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 99 "..\..\Views\Profile\Index.cshtml"
                           Write(Html.ValidationMessageFor(model => model.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n\r\n\r\n       " +
"                 <div");

WriteLiteral(" class=\"space-4\"");

WriteLiteral("></div>\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(" for=\"form-field-pass2\"");

WriteLiteral(">Confirma nova senha</label>\r\n\r\n                            <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 110 "..\..\Views\Profile\Index.cshtml"
                           Write(Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 111 "..\..\Views\Profile\Index.cshtml"
                           Write(Html.ValidationMessageFor(model => model.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"         </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n   " +
" </div>\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"form-actions no-color\"");

WriteLiteral(">\r\n        <div>\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" title=\"Salvar\"");

WriteLiteral(">Salvar <i");

WriteLiteral(" class=\"glyphicon glyphicon-floppy-disk\"");

WriteLiteral("></i></button> |\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5040), Tuple.Create("\"", 5074)
            
            #line 123 "..\..\Views\Profile\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5047), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 5047), false)
);

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" title=\"Ir para página inicial\"");

WriteLiteral(">Ir para página inicial <i");

WriteLiteral(" class=\"fa fa-home\"");

WriteLiteral("></i></a>\r\n        </div>\r\n    </div>\r\n</form>");

        }
    }
}
#pragma warning restore 1591
