CREATE TABLE [Security].[AudAgrupamento]
(
	[Id] BIGINT NOT NULL IDENTITY(1,1),
	[Ocorrencia] VARCHAR(15) NOT NULL,
	[Horario] DATETIME NOT NULL,
	[UsuarioId] BIGINT NOT NULL,
	[GrupoId] BIGINT NOT NULL,
	[RECCREATEDON] DATETIME NULL,
	[RECCREATEDBY] VARCHAR(65),
	[RECMODIFIEDON] DATETIME NULL,
	[RECMODIFIEDBY] VARCHAR(65)
);