CREATE TABLE [Security].[AudPermissao]
(
	[Id] BIGINT NOT NULL IDENTITY(1,1),
	[Ocorrencia] VARCHAR(15) NOT NULL,
	[Horario] DATETIME NOT NULL,
	[PermissaoId] BIGINT NOT NULL,
	[RecursoId] BIGINT NULL,
	[RelatorioId] BIGINT NULL,
	[GrupoId] BIGINT NULL,
	[UsuarioId] BIGINT NULL,
	[Visualizar] BIT NULL,
	[Inserir] BIT NULL,
	[Alterar] BIT NULL,
	[Excluir] BIT NULL,
	[RECCREATEDON] DATETIME NULL,
	[RECCREATEDBY] VARCHAR(65),
	[RECMODIFIEDON] DATETIME NULL,
	[RECMODIFIEDBY] VARCHAR(65),
	[RECDELETEDON] DATETIME NULL,
	[RECDELETEDBY] VARCHAR(65),

	CONSTRAINT [PK_Security.AudPermissao] PRIMARY KEY(Id)
);
