#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Login/Index.cshtml")]
    public partial class _Views_Login_Index_cshtml : System.Web.Mvc.WebViewPage<LVSA.Base.Presentation.ViewModels.LoginViewModel>
    {
        public _Views_Login_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Login\Index.cshtml"
  
    string serverCDN = System.Web.Configuration.WebConfigurationManager.AppSettings["Address_LVSA.CDN.Presentation"];

    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewBag.Title = "Informe seus dados";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 10 "..\..\Views\Login\Index.cshtml"
 using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @id = "Login" }))
{


            
            #line default
            #line hidden
WriteLiteral("    <!-- Login -->\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"lc-block toggled\"");

WriteLiteral(" id=\"l-login\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"input-group m-b-20\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-arrow-right\"");

WriteLiteral("></i></span>\r\n            <div");

WriteLiteral(" class=\"fg-line\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Views\Login\Index.cshtml"
           Write(Html.TextBoxFor(model => model.Usuario, new { @class = "form-control", @placeholder = "Código de acesso ou e-mail", @required = "requerid" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

WriteLiteral("            ");

            
            #line 21 "..\..\Views\Login\Index.cshtml"
       Write(Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n\r\n        <div");

WriteLiteral(" class=\"input-group m-b-20\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-arrow-right\"");

WriteLiteral("></i></span>\r\n            <div");

WriteLiteral(" class=\"fg-line\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 28 "..\..\Views\Login\Index.cshtml"
           Write(Html.PasswordFor(model => model.Senha, new { @class = "form-control", @placeholder = "Senha", @required = "required" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\Login\Index.cshtml"
       Write(Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n\r\n        <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-login btn-danger btn-float\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-arrow-forward\"");

WriteLiteral("></i></button>\r\n\r\n        <ul");

WriteLiteral(" class=\"login-navigation\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" data-block=\"#l-register\"");

WriteLiteral(" class=\"bgm-red\"");

WriteLiteral(">Register</li>\r\n            <li");

WriteLiteral(" data-block=\"#l-forget-password\"");

WriteLiteral(" class=\"bgm-orange\"");

WriteLiteral(">Forgot Password?</li>\r\n        </ul>\r\n\r\n    </div>\r\n");

            
            #line 44 "..\..\Views\Login\Index.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <!-- Register -->\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"lc-block\"");

WriteLiteral(" id=\"l-register\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"input-group m-b-20\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-account\"");

WriteLiteral("></i></span>\r\n            <div");

WriteLiteral(" class=\"fg-line\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Username\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"input-group m-b-20\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-email\"");

WriteLiteral("></i></span>\r\n            <div");

WriteLiteral(" class=\"fg-line\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Email Address\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"input-group m-b-20\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-male\"");

WriteLiteral("></i></span>\r\n            <div");

WriteLiteral(" class=\"fg-line\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Password\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n\r\n        <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n            <label>\r\n                <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"input-helper\"");

WriteLiteral("></i>\r\n                Accept the license agreement\r\n            </label>\r\n      " +
"  </div>\r\n\r\n        <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" class=\"btn btn-login btn-danger btn-float\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-arrow-forward\"");

WriteLiteral("></i></a>\r\n\r\n        <ul");

WriteLiteral(" class=\"login-navigation\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" data-block=\"#l-login\"");

WriteLiteral(" class=\"bgm-green\"");

WriteLiteral(">Login</li>\r\n            <li");

WriteLiteral(" data-block=\"#l-forget-password\"");

WriteLiteral(" class=\"bgm-orange\"");

WriteLiteral(">Forgot Password?</li>\r\n        </ul>\r\n    </div>\r\n");

            
            #line 85 "..\..\Views\Login\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <!-- Forgot Password -->\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"lc-block\"");

WriteLiteral(" id=\"l-forget-password\"");

WriteLiteral(">\r\n        <p");

WriteLiteral(" class=\"text-left\"");

WriteLiteral(">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eu risus. Curabit" +
"ur commodo lorem fringilla enim feugiat commodo sed ac lacus.</p>\r\n\r\n        <di" +
"v");

WriteLiteral(" class=\"input-group m-b-20\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-email\"");

WriteLiteral("></i></span>\r\n            <div");

WriteLiteral(" class=\"fg-line\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Email Address\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n\r\n        <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" class=\"btn btn-login btn-danger btn-float\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-arrow-forward\"");

WriteLiteral("></i></a>\r\n\r\n        <ul");

WriteLiteral(" class=\"login-navigation\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" data-block=\"#l-login\"");

WriteLiteral(" class=\"bgm-green\"");

WriteLiteral(">Login</li>\r\n            <li");

WriteLiteral(" data-block=\"#l-register\"");

WriteLiteral(" class=\"bgm-red\"");

WriteLiteral(">Register</li>\r\n        </ul>\r\n    </div>\r\n");

            
            #line 104 "..\..\Views\Login\Index.cshtml"

}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"white\"");

WriteLiteral(">© ");

            
            #line 108 "..\..\Views\Login\Index.cshtml"
                     Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" – Housing ");

WriteLiteral("@ Leonelleo</span>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
