#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Social.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_PartialView/Notificacoes.cshtml")]
    public partial class _Views_Shared__PartialView_Notificacoes_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__PartialView_Notificacoes_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<li");

WriteLiteral(" class=\"transparent\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"ace-icon fa fa-bell icon-animated-bell\"");

WriteLiteral("></i>\r\n        <span");

WriteLiteral(" class=\"badge badge-important\"");

WriteLiteral(">8</span>\r\n    </a>\r\n\r\n    <ul");

WriteLiteral(" class=\"dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-ca" +
"ret dropdown-close\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"ace-icon fa fa-exclamation-triangle\"");

WriteLiteral("></i>\r\n            8 Mensagens\r\n        </li>\r\n\r\n        <li");

WriteLiteral(" class=\"dropdown-content\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-navbar navbar-pink\"");

WriteLiteral(">\r\n                <li>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"btn btn-xs no-hover btn-pink fa fa-comment\"");

WriteLiteral("></i>\r\n                                New Comments\r\n                            " +
"</span>\r\n                            <span");

WriteLiteral(" class=\"pull-right badge badge-info\"");

WriteLiteral(">+12</span>\r\n                        </div>\r\n                    </a>\r\n          " +
"      </li>\r\n\r\n                <li>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"btn btn-xs btn-primary fa fa-user\"");

WriteLiteral("></i>\r\n                        Bob just signed up as an editor ...\r\n             " +
"       </a>\r\n                </li>\r\n\r\n                <li>\r\n                    " +
"<a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"btn btn-xs no-hover btn-success fa fa-shopping-cart\"");

WriteLiteral("></i>\r\n                                New Orders\r\n                            </" +
"span>\r\n                            <span");

WriteLiteral(" class=\"pull-right badge badge-success\"");

WriteLiteral(">+8</span>\r\n                        </div>\r\n                    </a>\r\n           " +
"     </li>\r\n\r\n                <li>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"btn btn-xs no-hover btn-info fa fa-twitter\"");

WriteLiteral("></i>\r\n                                Followers\r\n                            </s" +
"pan>\r\n                            <span");

WriteLiteral(" class=\"pull-right badge badge-info\"");

WriteLiteral(">+11</span>\r\n                        </div>\r\n                    </a>\r\n          " +
"      </li>\r\n            </ul>\r\n        </li>\r\n\r\n        <li");

WriteLiteral(" class=\"dropdown-footer\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                Ver todas notificações\r\n                ");

WriteLiteral("\r\n            </a>\r\n        </li>\r\n    </ul>\r\n</li>");

        }
    }
}
#pragma warning restore 1591
