#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_PartialView/Atalhos.cshtml")]
    public partial class _Views_Shared__PartialView_Atalhos_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__PartialView_Atalhos_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<li>\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 12), Tuple.Create("\"", 46)
            
            #line 2 "..\..\Views\Shared\_PartialView\Atalhos.cshtml"
, Tuple.Create(Tuple.Create("", 19), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 19), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"ace-icon fa fa-home home-icon\"");

WriteLiteral("></i></a>\r\n</li>");

        }
    }
}
#pragma warning restore 1591
