#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_PartialView/Gritter.cshtml")]
    public partial class _Views_Shared__PartialView_Gritter_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__PartialView_Gritter_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
  
    IEnumerable<LVSA.Base.Presentation.ViewModels.GritterViewModel> gritters = (IEnumerable<LVSA.Base.Presentation.ViewModels.GritterViewModel>)TempData["LVSA.CDN.Plugins.Gritter"];

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 5 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
 if (gritters != null && gritters.Count() > 0)
{

    foreach (var gritter in gritters)
    {
        gritter.Message = gritter.Message.Replace("\n", "");

        if (gritter.Style == LVSA.Base.Presentation.ViewModels.GritterStyle.Warning)
        {

            
            #line default
            #line hidden
WriteLiteral("            <script>\r\n                var teste = LVSA.CDN.Plugins.Gritter.Warnin" +
"g(\'<i class=\"fa fa-exclamation-triangle\"></i> ");

            
            #line 15 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                    Write(gritter.Tittle);

            
            #line default
            #line hidden
WriteLiteral("\',\'");

            
            #line 15 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                                      Write(gritter.Message);

            
            #line default
            #line hidden
WriteLiteral("\', ");

            
            #line 15 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                                                          Write(gritter.Center ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 15 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                                                                                                Write(gritter.Sticky ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(");\r\n            </script>\r\n");

            
            #line 17 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
        }
        else if (gritter.Style == LVSA.Base.Presentation.ViewModels.GritterStyle.Success)
        {

            
            #line default
            #line hidden
WriteLiteral("            <script>\r\n                var teste = LVSA.CDN.Plugins.Gritter.Succes" +
"s(\'<i class=\"fa fa-check\"></i> ");

            
            #line 21 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                     Write(gritter.Tittle);

            
            #line default
            #line hidden
WriteLiteral("\',\'");

            
            #line 21 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                       Write(gritter.Message);

            
            #line default
            #line hidden
WriteLiteral("\', ");

            
            #line 21 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                                           Write(gritter.Center ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 21 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                                                                                 Write(gritter.Sticky ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(");\r\n            </script>\r\n");

            
            #line 23 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
        }
        else if (gritter.Style == LVSA.Base.Presentation.ViewModels.GritterStyle.Error)
        {

            
            #line default
            #line hidden
WriteLiteral("            <script>\r\n                var teste = LVSA.CDN.Plugins.Gritter.Error(" +
"\'<i class=\"fa fa-remove\"></i> ");

            
            #line 27 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                    Write(gritter.Tittle);

            
            #line default
            #line hidden
WriteLiteral("\',\'");

            
            #line 27 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                      Write(gritter.Message);

            
            #line default
            #line hidden
WriteLiteral("\', ");

            
            #line 27 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                                          Write(gritter.Center ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 27 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                                                                                Write(gritter.Sticky ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(");\r\n            </script>\r\n");

            
            #line 29 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
        }
        else if (gritter.Style == LVSA.Base.Presentation.ViewModels.GritterStyle.Information)
        {

            
            #line default
            #line hidden
WriteLiteral("            <script>\r\n                var teste = LVSA.CDN.Plugins.Gritter.Inform" +
"ation(\'<i class=\"fa fa-bullhorn\"></i> ");

            
            #line 33 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                            Write(gritter.Tittle);

            
            #line default
            #line hidden
WriteLiteral("\',\'");

            
            #line 33 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                              Write(gritter.Message);

            
            #line default
            #line hidden
WriteLiteral("\', ");

            
            #line 33 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                                                  Write(gritter.Center ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 33 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                                                                                        Write(gritter.Sticky ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(");\r\n            </script>\r\n");

            
            #line 35 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <script>\r\n                var teste = LVSA.CDN.Plugins.Gritter.Defaul" +
"t(\'<i class=\"fa fa-bolt\"></i> ");

            
            #line 39 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                    Write(gritter.Tittle);

            
            #line default
            #line hidden
WriteLiteral("\',\'");

            
            #line 39 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                      Write(gritter.Message);

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 39 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                                           Write(gritter.Center ? "gritter-center" : "");

            
            #line default
            #line hidden
WriteLiteral("\', ");

            
            #line 39 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
                                                                                                                                                                       Write(gritter.Sticky ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(");\r\n            </script>\r\n");

            
            #line 41 "..\..\Views\Shared\_PartialView\Gritter.cshtml"
        }
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
