#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_PartialView/Navbar.cshtml")]
    public partial class _Views_Shared__PartialView_Navbar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__PartialView_Navbar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_PartialView\Navbar.cshtml"
  
    string serverCDN = System.Web.Configuration.WebConfigurationManager.AppSettings["Address_LVSA.CDN.Presentation"];

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 5 "..\..\Views\Shared\_PartialView\Navbar.cshtml"
 if (TempData["Navbar"] != null)
{
    
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\Shared\_PartialView\Navbar.cshtml"
Write(new HtmlString((string)TempData["Navbar"]));

            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\Shared\_PartialView\Navbar.cshtml"
                                                 
}


            
            #line default
            #line hidden
            
            #line 121 "..\..\Views\Shared\_PartialView\Navbar.cshtml"
       
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
