#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_PartialView/Recursos.cshtml")]
    public partial class _Views_Shared__PartialView_Recursos_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<LVSA.Security.Application.ViewModels.RecursoViewModel>>
    {
        public _Views_Shared__PartialView_Recursos_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
  
    var Seguranca = ((LVSA.Security.Application.Models.Seguranca)TempData["Seguranca"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 7 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
 foreach (var i in Model.Where(w => w.Ativo && Seguranca.RecursoSet.Select(s => s.Id).Contains(w.Id) && w.TipoRecurso.Codigo == "MN").OrderByDescending(o => o.Peso))
{

            
            #line default
            #line hidden
WriteLiteral("    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 353), Tuple.Create("\"", 529)
, Tuple.Create(Tuple.Create("", 361), Tuple.Create("hover", 361), true)
            
            #line 9 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
, Tuple.Create(Tuple.Create(" ", 366), Tuple.Create<System.Object, System.Int32>(TempData["##TempHover"]
            
            #line default
            #line hidden
, 367), false)
            
            #line 9 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
, Tuple.Create(Tuple.Create(" ", 391), Tuple.Create<System.Object, System.Int32>(TempData["Recurso"] != null && ((LVSA.Security.Application.ViewModels.RecursoViewModel)TempData["Recurso"]).Id == i.Id ? "active" : ""
            
            #line default
            #line hidden
, 392), false)
);

WriteLiteral(">\r\n        <a");

WriteLiteral(" data-id=\"");

            
            #line 10 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
               Write(i.Controller);

            
            #line default
            #line hidden
WriteLiteral("#");

            
            #line 10 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
                             Write(i.Action);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("title", Tuple.Create(" title=\"", 577), Tuple.Create("\"", 596)
            
            #line 10 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
, Tuple.Create(Tuple.Create("", 585), Tuple.Create<System.Object, System.Int32>(i.Exibicao
            
            #line default
            #line hidden
, 585), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 597), Tuple.Create("\"", 823)
            
            #line 10 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
, Tuple.Create(Tuple.Create("", 604), Tuple.Create<System.Object, System.Int32>(i.RecursoSet != null && i.RecursoSet.Where(w => Seguranca.RecursoSet.Select(s => s.Id).Contains(w.Id) && w.TipoRecurso.Codigo == "MN").Count() > 0 ? "javascript:void(0);" : Url.Action(i.Action, i.Controller, new { })
            
            #line default
            #line hidden
, 604), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 824), Tuple.Create("\"", 1006)
            
            #line 10 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
                                                                                                                                                                                                                             , Tuple.Create(Tuple.Create("", 832), Tuple.Create<System.Object, System.Int32>(i.RecursoSet != null && i.RecursoSet.Where(w => Seguranca.RecursoSet.Select(s => s.Id).Contains(w.Id) && w.TipoRecurso.Codigo == "MN").Count() > 0 ? "dropdown-toggle" : ""
            
            #line default
            #line hidden
, 832), false)
);

WriteLiteral(">\r\n\r\n        <i");

WriteAttribute("class", Tuple.Create(" class=\"", 1022), Tuple.Create("\"", 1047)
, Tuple.Create(Tuple.Create("", 1030), Tuple.Create("menu-icon", 1030), true)
            
            #line 12 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
, Tuple.Create(Tuple.Create(" ", 1039), Tuple.Create<System.Object, System.Int32>(i.Icon
            
            #line default
            #line hidden
, 1040), false)
);

WriteLiteral(">\r\n        </i>\r\n        <span");

WriteLiteral(" class=\"menu-text\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
    Write(i.Exibicao.Count() > 16 ? i.Exibicao.Substring(0, 16) + "..." : i.Exibicao);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n\r\n        <b");

WriteAttribute("class", Tuple.Create(" class=\"", 1215), Tuple.Create("\"", 1405)
            
            #line 18 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
, Tuple.Create(Tuple.Create("", 1223), Tuple.Create<System.Object, System.Int32>(i.RecursoSet != null && i.RecursoSet.Where(w => Seguranca.RecursoSet.Select(s => s.Id).Contains(w.Id) && w.TipoRecurso.Codigo == "MN").Count() > 0 ? "arrow fa fa-angle-down" : ""
            
            #line default
            #line hidden
, 1223), false)
, Tuple.Create(Tuple.Create(" ", 1404), Tuple.Create("", 1404), true)
);

WriteLiteral("></b>\r\n        </a>\r\n\r\n        <b");

WriteLiteral(" class=\"arrow\"");

WriteLiteral("></b>\r\n\r\n");

            
            #line 23 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
        
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
         if (i.RecursoSet != null && i.RecursoSet.Where(w => Seguranca.RecursoSet.Select(s => s.Id).Contains(w.Id) && w.TipoRecurso.Codigo == "MN").Count() > 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <ul");

WriteLiteral(" class=\"submenu\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 26 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
           Write(Html.Partial("_PartialView/Recursos", i.RecursoSet.Where(w => Seguranca.RecursoSet.Select(s => s.Id).Contains(w.Id) && w.TipoRecurso.Codigo == "MN")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </ul>\r\n");

            
            #line 28 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li>\r\n");

            
            #line 31 "..\..\Views\Shared\_PartialView\Recursos.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
