#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_PartialView/Sidebar.cshtml")]
    public partial class _Views_Shared__PartialView_Sidebar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__PartialView_Sidebar_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<li");

WriteLiteral(" class=\"hover\"");

WriteLiteral(">\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 28), Tuple.Create("\"", 62)
            
            #line 3 "..\..\Views\Shared\_PartialView\Sidebar.cshtml"
, Tuple.Create(Tuple.Create("", 35), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 35), false)
);

WriteLiteral(">\r\n\r\n        <i");

WriteLiteral(" class=\"menu-icon fa fa-home\"");

WriteLiteral("></i>\r\n        <span");

WriteLiteral(" class=\"menu-text\"");

WriteLiteral(">\r\n            Página inicial\r\n        </span>\r\n\r\n        ");

WriteLiteral("\r\n    </a>\r\n    <b");

WriteLiteral(" class=\"arrow\"");

WriteLiteral("></b>\r\n</li>");

        }
    }
}
#pragma warning restore 1591
