#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout3.cshtml")]
    public partial class _Views_Shared__Layout3_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout3_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_Layout3.cshtml"
  
    string serverCDN = System.Web.Configuration.WebConfigurationManager.AppSettings["Address_LVSA.CDN.Presentation"];


    LVSA.Security.Application.Models.Seguranca Seguranca = ((LVSA.Security.Application.Models.Seguranca)TempData["Seguranca"]);


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<!--[if IE 9 ]><html class=\"ie9\"><![endif]-->\r\n<he" +
"ad>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(">\r\n    <title>Material Admin</title>\r\n\r\n    <!-- Vendor CSS -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 577), Tuple.Create("\"", 686)
            
            #line 20 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 584), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 584), false)
, Tuple.Create(Tuple.Create("", 596), Tuple.Create("Content/Templates/Material/vendors/bower_components/fullcalendar/dist/fullcalenda" +
"r.min.css", 596), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 716), Tuple.Create("\"", 814)
            
            #line 21 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 723), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 723), false)
, Tuple.Create(Tuple.Create("", 735), Tuple.Create("Content/Templates/Material/vendors/bower_components/animate.css/animate.min.css", 735), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 844), Tuple.Create("\"", 955)
            
            #line 22 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 851), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 851), false)
, Tuple.Create(Tuple.Create("", 863), Tuple.Create("Content/Templates/Material/vendors/bower_components/bootstrap-sweetalert/lib/swee" +
"t-alert.css", 863), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 985), Tuple.Create("\"", 1128)
            
            #line 23 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 992), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 992), false)
, Tuple.Create(Tuple.Create("", 1004), Tuple.Create("Content/Templates/Material/vendors/bower_components/material-design-iconic-font/d" +
"ist/css/material-design-iconic-font.min.css", 1004), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1177), Tuple.Create("\"", 1245)
            
            #line 25 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 1184), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1184), false)
, Tuple.Create(Tuple.Create("", 1196), Tuple.Create("Content/Templates/Ace/assets/css/font-awesome.css", 1196), true)
);

WriteLiteral(" />\r\n\r\n    <!-- CSS -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1280), Tuple.Create("\"", 1343)
            
            #line 28 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 1287), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1287), false)
, Tuple.Create(Tuple.Create("", 1299), Tuple.Create("Content/Templates/Material/css/app.min.1.css", 1299), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1373), Tuple.Create("\"", 1436)
            
            #line 29 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 1380), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1380), false)
, Tuple.Create(Tuple.Create("", 1392), Tuple.Create("Content/Templates/Material/css/app.min.2.css", 1392), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n\r\n</head>\r\n<body>\r\n    <header");

WriteLiteral(" id=\"header\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" class=\"header-inner\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" id=\"menu-trigger\"");

WriteLiteral(" data-trigger=\"#sidebar\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"line-wrap\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"line top\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"line center\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"line bottom\"");

WriteLiteral("></div>\r\n                </div>\r\n            </li>\r\n\r\n            <li");

WriteLiteral(" class=\"logo hidden-xs\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"index.html\"");

WriteLiteral(">Material Admin</a>\r\n            </li>\r\n\r\n            <li");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"top-menu\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" id=\"toggle-width\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"toggle-switch\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" id=\"tw-switch\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" hidden=\"hidden\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"tw-switch\"");

WriteLiteral(" class=\"ts-helper\"");

WriteLiteral("></label>\r\n                        </div>\r\n                    </li>\r\n           " +
"         <li");

WriteLiteral(" id=\"top-search\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" class=\"tm-search\"");

WriteLiteral(" href=\"\"");

WriteLiteral("></a>\r\n                    </li>\r\n                    <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" class=\"tm-message\"");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"tmn-counts\"");

WriteLiteral(">6</i></a>\r\n                        <div");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-lg pull-right\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"listview\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"lv-header\"");

WriteLiteral(">\r\n                                    Messages\r\n                                " +
"</div>\r\n                                <div");

WriteLiteral(" class=\"lv-body\"");

WriteLiteral(">\r\n                                    <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/1.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"                  <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">David Belle</div>\r\n                                                <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Cum sociis natoque penatibus et magnis dis parturient montes</small>\r\n          " +
"                                  </div>\r\n                                      " +
"  </div>\r\n                                    </a>\r\n                            " +
"        <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/2.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"                  <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Jonathan Morris</div>\r\n                                                <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(@">Nunc quis diam diamurabitur at dolor elementum, dictum turpis vel</small>
                                            </div>
                                        </div>
                                    </a>
                                    <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/3.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"                  <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Fredric Mitchell Jr.</div>\r\n                                                <sma" +
"ll");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(@">Phasellus a ante et est ornare accumsan at vel magnauis blandit turpis at augue ultricies</small>
                                            </div>
                                        </div>
                                    </a>
                                    <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/4.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"                  <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Glenn Jecobs</div>\r\n                                                <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(@">Ut vitae lacus sem ellentesque maximus, nunc sit amet varius dignissim, dui est consectetur neque</small>
                                            </div>
                                        </div>
                                    </a>
                                    <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/4.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"                  <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Bill Phillips</div>\r\n                                                <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(@">Proin laoreet commodo eros id faucibus. Donec ligula quam, imperdiet vel ante placerat</small>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <a");

WriteLiteral(" class=\"lv-footer\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">View All</a>\r\n                            </div>\r\n                        </div>" +
"\r\n                    </li>\r\n                    <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" class=\"tm-notification\"");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"tmn-counts\"");

WriteLiteral(">9</i></a>\r\n                        <div");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-lg pull-right\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"listview\"");

WriteLiteral(" id=\"notifications\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"lv-header\"");

WriteLiteral(">\r\n                                    Notification\r\n\r\n                          " +
"          <ul");

WriteLiteral(" class=\"actions\"");

WriteLiteral(">\r\n                                        <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                                            <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" data-clear=\"notification\"");

WriteLiteral(">\r\n                                                <i");

WriteLiteral(" class=\"zmdi zmdi-check-all\"");

WriteLiteral("></i>\r\n                                            </a>\r\n                        " +
"                </li>\r\n                                    </ul>\r\n              " +
"                  </div>\r\n                                <div");

WriteLiteral(" class=\"lv-body\"");

WriteLiteral(">\r\n                                    <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/1.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"                  <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">David Belle</div>\r\n                                                <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Cum sociis natoque penatibus et magnis dis parturient montes</small>\r\n          " +
"                                  </div>\r\n                                      " +
"  </div>\r\n                                    </a>\r\n                            " +
"        <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/2.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"                  <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Jonathan Morris</div>\r\n                                                <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(@">Nunc quis diam diamurabitur at dolor elementum, dictum turpis vel</small>
                                            </div>
                                        </div>
                                    </a>
                                    <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/3.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"                  <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Fredric Mitchell Jr.</div>\r\n                                                <sma" +
"ll");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(@">Phasellus a ante et est ornare accumsan at vel magnauis blandit turpis at augue ultricies</small>
                                            </div>
                                        </div>
                                    </a>
                                    <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/4.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"                  <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Glenn Jecobs</div>\r\n                                                <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(@">Ut vitae lacus sem ellentesque maximus, nunc sit amet varius dignissim, dui est consectetur neque</small>
                                            </div>
                                        </div>
                                    </a>
                                    <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/4.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"                  <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Bill Phillips</div>\r\n                                                <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(@">Proin laoreet commodo eros id faucibus. Donec ligula quam, imperdiet vel ante placerat</small>
                                            </div>
                                        </div>
                                    </a>
                                </div>

                                <a");

WriteLiteral(" class=\"lv-footer\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">View Previous</a>\r\n                            </div>\r\n\r\n                       " +
" </div>\r\n                    </li>\r\n                    <li");

WriteLiteral(" class=\"dropdown hidden-xs\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" class=\"tm-task\"");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"tmn-counts\"");

WriteLiteral(">2</i></a>\r\n                        <div");

WriteLiteral(" class=\"dropdown-menu pull-right dropdown-menu-lg\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"listview\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"lv-header\"");

WriteLiteral(">\r\n                                    Tasks\r\n                                </d" +
"iv>\r\n                                <div");

WriteLiteral(" class=\"lv-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"lv-title m-b-5\"");

WriteLiteral(">HTML5 Validation Report</div>\r\n\r\n                                        <div");

WriteLiteral(" class=\"progress\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"progress-bar\"");

WriteLiteral(" role=\"progressbar\"");

WriteLiteral(" aria-valuenow=\"95\"");

WriteLiteral(" aria-valuemin=\"0\"");

WriteLiteral(" aria-valuemax=\"100\"");

WriteLiteral(" style=\"width: 95%\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">95% Complete (success)</span>\r\n                                            </div" +
">\r\n                                        </div>\r\n                             " +
"       </div>\r\n                                    <div");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"lv-title m-b-5\"");

WriteLiteral(">Google Chrome Extension</div>\r\n\r\n                                        <div");

WriteLiteral(" class=\"progress\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"progress-bar progress-bar-success\"");

WriteLiteral(" role=\"progressbar\"");

WriteLiteral(" aria-valuenow=\"80\"");

WriteLiteral(" aria-valuemin=\"0\"");

WriteLiteral(" aria-valuemax=\"100\"");

WriteLiteral(" style=\"width: 80%\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">80% Complete (success)</span>\r\n                                            </div" +
">\r\n                                        </div>\r\n                             " +
"       </div>\r\n                                    <div");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"lv-title m-b-5\"");

WriteLiteral(">Social Intranet Projects</div>\r\n\r\n                                        <div");

WriteLiteral(" class=\"progress\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"progress-bar progress-bar-info\"");

WriteLiteral(" role=\"progressbar\"");

WriteLiteral(" aria-valuenow=\"20\"");

WriteLiteral(" aria-valuemin=\"0\"");

WriteLiteral(" aria-valuemax=\"100\"");

WriteLiteral(" style=\"width: 20%\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">20% Complete</span>\r\n                                            </div>\r\n       " +
"                                 </div>\r\n                                    </d" +
"iv>\r\n                                    <div");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"lv-title m-b-5\"");

WriteLiteral(">Bootstrap Admin Template</div>\r\n\r\n                                        <div");

WriteLiteral(" class=\"progress\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"progress-bar progress-bar-warning\"");

WriteLiteral(" role=\"progressbar\"");

WriteLiteral(" aria-valuenow=\"60\"");

WriteLiteral(" aria-valuemin=\"0\"");

WriteLiteral(" aria-valuemax=\"100\"");

WriteLiteral(" style=\"width: 60%\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">60% Complete (warning)</span>\r\n                                            </div" +
">\r\n                                        </div>\r\n                             " +
"       </div>\r\n                                    <div");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"lv-title m-b-5\"");

WriteLiteral(">Youtube Client App</div>\r\n\r\n                                        <div");

WriteLiteral(" class=\"progress\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"progress-bar progress-bar-danger\"");

WriteLiteral(" role=\"progressbar\"");

WriteLiteral(" aria-valuenow=\"80\"");

WriteLiteral(" aria-valuemin=\"0\"");

WriteLiteral(" aria-valuemax=\"100\"");

WriteLiteral(" style=\"width: 80%\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">80% Complete (danger)</span>\r\n                                            </div>" +
"\r\n                                        </div>\r\n                              " +
"      </div>\r\n                                </div>\r\n\r\n                        " +
"        <a");

WriteLiteral(" class=\"lv-footer\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">View All</a>\r\n                            </div>\r\n                        </div>" +
"\r\n                    </li>\r\n                    <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" class=\"tm-settings\"");

WriteLiteral(" href=\"\"");

WriteLiteral("></a>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu dm-icon pull-right\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" class=\"hidden-xs\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" data-action=\"fullscreen\"");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-fullscreen\"");

WriteLiteral("></i> Toggle Fullscreen</a>\r\n                            </li>\r\n                 " +
"           <li>\r\n                                <a");

WriteLiteral(" data-action=\"clear-localstorage\"");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-delete\"");

WriteLiteral("></i> Clear Local Storage</a>\r\n                            </li>\r\n               " +
"             <li>\r\n                                <a");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-face\"");

WriteLiteral("></i> Privacy Settings</a>\r\n                            </li>\r\n                  " +
"          <li>\r\n                                <a");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-settings\"");

WriteLiteral("></i> Other Settings</a>\r\n                            </li>\r\n                    " +
"    </ul>\r\n                    </li>\r\n                    <li");

WriteLiteral(" class=\"hidden-xs\"");

WriteLiteral(" id=\"chat-trigger\"");

WriteLiteral(" data-trigger=\"#chat\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" class=\"tm-chat\"");

WriteLiteral(" href=\"\"");

WriteLiteral("></a>\r\n                    </li>\r\n            </li>\r\n        </ul>\r\n\r\n        <!-" +
"- Top Search Content -->\r\n");

            
            #line 287 "..\..\Views\Shared\_Layout3.cshtml"
        
            
            #line default
            #line hidden
            
            #line 287 "..\..\Views\Shared\_Layout3.cshtml"
         using (Html.BeginForm("Index", "Pesquisa", FormMethod.Post, new { @class = "form-search" }))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"top-search-wrap\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" name=\"Pesquisa\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" id=\"top-search-close\"");

WriteLiteral(">&times;</i>\r\n            </div>\r\n");

            
            #line 293 "..\..\Views\Shared\_Layout3.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </header>\r\n    <section");

WriteLiteral(" id=\"main\"");

WriteLiteral(">\r\n        <aside");

WriteLiteral(" id=\"sidebar\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"sidebar-inner c-overflow\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"profile-menu\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"profile-pic\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" src=\"img/profile-pics/1.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"profile-info\"");

WriteLiteral(">\r\n                            Malinda Hollaway\r\n\r\n                            <i" +
"");

WriteLiteral(" class=\"zmdi zmdi-arrow-drop-down\"");

WriteLiteral("></i>\r\n                        </div>\r\n                    </a>\r\n\r\n              " +
"      <ul");

WriteLiteral(" class=\"main-menu\"");

WriteLiteral(">\r\n                        <li>\r\n                            <a");

WriteLiteral(" href=\"profile-about.html\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-account\"");

WriteLiteral("></i> View Profile</a>\r\n                        </li>\r\n                        <l" +
"i>\r\n                            <a");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-input-antenna\"");

WriteLiteral("></i> Privacy Settings</a>\r\n                        </li>\r\n                      " +
"  <li>\r\n                            <a");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-settings\"");

WriteLiteral("></i> Settings</a>\r\n                        </li>\r\n                        <li>\r\n" +
"                            <a");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-time-restore\"");

WriteLiteral("></i> Logout</a>\r\n                        </li>\r\n                    </ul>\r\n     " +
"           </div>\r\n\r\n                <ul");

WriteLiteral(" class=\"main-menu\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"index.html\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-home\"");

WriteLiteral("></i> Home</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"typography.html\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi zmdi-format-underlined\"");

WriteLiteral("></i> Typography</a></li>\r\n                    <li");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-widgets\"");

WriteLiteral("></i> Widgets</a>\r\n\r\n                        <ul>\r\n                            <l" +
"i><a");

WriteLiteral(" href=\"widget-templates.html\"");

WriteLiteral(">Templates</a></li>\r\n                            <li><a");

WriteLiteral(" class=\"active\"");

WriteLiteral(" href=\"widgets.html\"");

WriteLiteral(">Widgets</a></li>\r\n                        </ul>\r\n                    </li>\r\n    " +
"                <li");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-view-list\"");

WriteLiteral("></i> Tables</a>\r\n\r\n                        <ul>\r\n                            <li" +
"><a");

WriteLiteral(" href=\"tables.html\"");

WriteLiteral(">Normal Tables</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"data-tables.html\"");

WriteLiteral(">Data Tables</a></li>\r\n                        </ul>\r\n                    </li>\r\n" +
"                    <li");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-collection-text\"");

WriteLiteral("></i> Forms</a>\r\n\r\n                        <ul>\r\n                            <li>" +
"<a");

WriteLiteral(" href=\"form-elements.html\"");

WriteLiteral(">Basic Form Elements</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"form-components.html\"");

WriteLiteral(">Form Components</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"form-examples.html\"");

WriteLiteral(">Form Examples</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"form-validations.html\"");

WriteLiteral(">Form Validation</a></li>\r\n                        </ul>\r\n                    </l" +
"i>\r\n                    <li");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-swap-alt\"");

WriteLiteral("></i>User Interface</a>\r\n                        <ul>\r\n                          " +
"  <li><a");

WriteLiteral(" href=\"colors.html\"");

WriteLiteral(">Colors</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"animations.html\"");

WriteLiteral(">Animations</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"box-shadow.html\"");

WriteLiteral(">Box Shadow</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"buttons.html\"");

WriteLiteral(">Buttons</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"icons.html\"");

WriteLiteral(">Icons</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"alerts.html\"");

WriteLiteral(">Alerts</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"notification-dialog.html\"");

WriteLiteral(">Notifications & Dialogs</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"media.html\"");

WriteLiteral(">Media</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"components.html\"");

WriteLiteral(">Components</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"other-components.html\"");

WriteLiteral(">Others</a></li>\r\n                        </ul>\r\n                    </li>\r\n     " +
"               <li");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-trending-up\"");

WriteLiteral("></i>Charts</a>\r\n                        <ul>\r\n                            <li><a" +
"");

WriteLiteral(" href=\"flot-charts.html\"");

WriteLiteral(">Flot Charts</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"other-charts.html\"");

WriteLiteral(">Other Charts</a></li>\r\n                        </ul>\r\n                    </li>\r" +
"\n                    <li><a");

WriteLiteral(" href=\"calendar.html\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-calendar\"");

WriteLiteral("></i> Calendar</a></li>\r\n                    <li");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-image\"");

WriteLiteral("></i>Photo Gallery</a>\r\n                        <ul>\r\n                           " +
" <li><a");

WriteLiteral(" href=\"photos.html\"");

WriteLiteral(">Default</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"photo-timeline.html\"");

WriteLiteral(">Timeline</a></li>\r\n                        </ul>\r\n                    </li>\r\n\r\n " +
"                   <li><a");

WriteLiteral(" href=\"generic-classes.html\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-layers\"");

WriteLiteral("></i> Generic Classes</a></li>\r\n                    <li");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"zmdi zmdi-collection-item\"");

WriteLiteral("></i> Sample Pages</a>\r\n                        <ul>\r\n\r\n                         " +
"   <li><a");

WriteLiteral(" href=\"profile-about.html\"");

WriteLiteral(">Profile</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"list-view.html\"");

WriteLiteral(">List View</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"messages.html\"");

WriteLiteral(">Messages</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"pricing-table.html\"");

WriteLiteral(">Pricing Table</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"contacts.html\"");

WriteLiteral(">Contacts</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"wall.html\"");

WriteLiteral(">Wall</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"invoice.html\"");

WriteLiteral(">Invoice</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"login.html\"");

WriteLiteral(">Login and Sign Up</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"lockscreen.html\"");

WriteLiteral(">Lockscreen</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"404.html\"");

WriteLiteral(">Error 404</a></li>\r\n\r\n                        </ul>\r\n                    </li>\r\n" +
"                </ul>\r\n            </div>\r\n        </aside>\r\n\r\n        <aside");

WriteLiteral(" id=\"chat\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"tab-nav tn-justified\"");

WriteLiteral(" role=\"tablist\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#friends\"");

WriteLiteral(" aria-controls=\"friends\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Friends</a></li>\r\n                <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#online\"");

WriteLiteral(" aria-controls=\"online\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Online Now</a></li>\r\n            </ul>\r\n\r\n            <div");

WriteLiteral(" class=\"chat-search\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"fg-line\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Search People\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" class=\"tab-pane fade in active\"");

WriteLiteral(" id=\"friends\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"listview\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-left p-relative\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/2.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"chat-status-busy\"");

WriteLiteral("></i>\r\n                                </div>\r\n                                <d" +
"iv");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Jonathan Morris</div>\r\n                                    <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Available</small>\r\n                                </div>\r\n                     " +
"       </div>\r\n                        </a>\r\n\r\n                        <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/1.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">David Belle</div>\r\n                                    <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Last seen 3 hours ago</small>\r\n                                </div>\r\n         " +
"                   </div>\r\n                        </a>\r\n\r\n                     " +
"   <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-left p-relative\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/3.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"chat-status-online\"");

WriteLiteral("></i>\r\n                                </div>\r\n                                <d" +
"iv");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Fredric Mitchell Jr.</div>\r\n                                    <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Availble</small>\r\n                                </div>\r\n                      " +
"      </div>\r\n                        </a>\r\n\r\n                        <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-left p-relative\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/4.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"chat-status-online\"");

WriteLiteral("></i>\r\n                                </div>\r\n                                <d" +
"iv");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Glenn Jecobs</div>\r\n                                    <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Availble</small>\r\n                                </div>\r\n                      " +
"      </div>\r\n                        </a>\r\n\r\n                        <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/5.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Bill Phillips</div>\r\n                                    <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Last seen 3 days ago</small>\r\n                                </div>\r\n          " +
"                  </div>\r\n                        </a>\r\n\r\n                      " +
"  <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/6.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Wendy Mitchell</div>\r\n                                    <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Last seen 2 minutes ago</small>\r\n                                </div>\r\n       " +
"                     </div>\r\n                        </a>\r\n                     " +
"   <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-left p-relative\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/7.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"chat-status-busy\"");

WriteLiteral("></i>\r\n                                </div>\r\n                                <d" +
"iv");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Teena Bell Ann</div>\r\n                                    <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Busy</small>\r\n                                </div>\r\n                          " +
"  </div>\r\n                        </a>\r\n                    </div>\r\n            " +
"    </div>\r\n                <div");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(" id=\"online\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"listview\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-left p-relative\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/2.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"chat-status-busy\"");

WriteLiteral("></i>\r\n                                </div>\r\n                                <d" +
"iv");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Jonathan Morris</div>\r\n                                    <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Available</small>\r\n                                </div>\r\n                     " +
"       </div>\r\n                        </a>\r\n\r\n                        <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-left p-relative\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/3.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"chat-status-online\"");

WriteLiteral("></i>\r\n                                </div>\r\n                                <d" +
"iv");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Fredric Mitchell Jr.</div>\r\n                                    <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Availble</small>\r\n                                </div>\r\n                      " +
"      </div>\r\n                        </a>\r\n\r\n                        <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-left p-relative\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/4.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"chat-status-online\"");

WriteLiteral("></i>\r\n                                </div>\r\n                                <d" +
"iv");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Glenn Jecobs</div>\r\n                                    <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Availble</small>\r\n                                </div>\r\n                      " +
"      </div>\r\n                        </a>\r\n\r\n                        <a");

WriteLiteral(" class=\"lv-item\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"media\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-left p-relative\"");

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"lv-img-sm\"");

WriteLiteral(" src=\"img/profile-pics/7.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"chat-status-busy\"");

WriteLiteral("></i>\r\n                                </div>\r\n                                <d" +
"iv");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"lv-title\"");

WriteLiteral(">Teena Bell Ann</div>\r\n                                    <small");

WriteLiteral(" class=\"lv-small\"");

WriteLiteral(">Busy</small>\r\n                                </div>\r\n                          " +
"  </div>\r\n                        </a>\r\n                    </div>\r\n            " +
"    </div>\r\n            </div>\r\n        </aside>\r\n\r\n        <section");

WriteLiteral(" id=\"content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"block-header\"");

WriteLiteral(">\r\n                    <h2>Form Components</h2>\r\n\r\n                    <ul");

WriteLiteral(" class=\"actions\"");

WriteLiteral(">\r\n                        <li>\r\n                            <a");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"zmdi zmdi-trending-up\"");

WriteLiteral("></i>\r\n                            </a>\r\n                        </li>\r\n         " +
"               <li>\r\n                            <a");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"zmdi zmdi-check-all\"");

WriteLiteral("></i>\r\n                            </a>\r\n                        </li>\r\n         " +
"               <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"zmdi zmdi-more-vert\"");

WriteLiteral("></i>\r\n                            </a>\r\n\r\n                            <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-right\"");

WriteLiteral(">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Refresh</a>\r\n                                </li>\r\n                            " +
"    <li>\r\n                                    <a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Manage Widgets</a>\r\n                                </li>\r\n                     " +
"           <li>\r\n                                    <a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Widgets Settings</a>\r\n                                </li>\r\n                   " +
"         </ul>\r\n                        </li>\r\n                    </ul>\r\n\r\n    " +
"            </div>\r\n\r\n                \r\n\r\n");

WriteLiteral("                        ");

            
            #line 610 "..\..\Views\Shared\_Layout3.cshtml"
                   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            </div>\r\n        </section>\r\n\r\n\r\n    </section>\r\n\r\n    <footer");

WriteLiteral(" id=\"footer\"");

WriteLiteral(">\r\n        Copyright &copy; 2015 Material Admin\r\n\r\n        <ul");

WriteLiteral(" class=\"f-menu\"");

WriteLiteral(">\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Home</a></li>\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Dashboard</a></li>\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Reports</a></li>\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Support</a></li>\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Contact</a></li>\r\n        </ul>\r\n    </footer>\r\n\r\n    <!-- Older IE warning mess" +
"age -->\r\n    <!--[if lt IE 9]>\r\n        <div class=\"ie-warning\">\r\n            <h" +
"1 class=\"c-white\">Warning!!</h1>\r\n            <p>You are using an outdated versi" +
"on of Internet Explorer, please upgrade <br/>to any of the following web browser" +
"s to access this website.</p>\r\n            <div class=\"iew-container\">\r\n        " +
"        <ul class=\"iew-download\">\r\n                    <li>\r\n                   " +
"     <a href=\"http://www.google.com/chrome/\">\r\n                            <img " +
"src=\"img/browsers/chrome.png\" alt=\"\">\r\n                            <div>Chrome</" +
"div>\r\n                        </a>\r\n                    </li>\r\n                 " +
"   <li>\r\n                        <a href=\"https://www.mozilla.org/en-US/firefox/" +
"new/\">\r\n                            <img src=\"img/browsers/firefox.png\" alt=\"\">\r" +
"\n                            <div>Firefox</div>\r\n                        </a>\r\n " +
"                   </li>\r\n                    <li>\r\n                        <a h" +
"ref=\"http://www.opera.com\">\r\n                            <img src=\"img/browsers/" +
"opera.png\" alt=\"\">\r\n                            <div>Opera</div>\r\n              " +
"          </a>\r\n                    </li>\r\n                    <li>\r\n           " +
"             <a href=\"https://www.apple.com/safari/\">\r\n                         " +
"   <img src=\"img/browsers/safari.png\" alt=\"\">\r\n                            <div>" +
"Safari</div>\r\n                        </a>\r\n                    </li>\r\n         " +
"           <li>\r\n                        <a href=\"http://windows.microsoft.com/e" +
"n-us/internet-explorer/download-ie\">\r\n                            <img src=\"img/" +
"browsers/ie.png\" alt=\"\">\r\n                            <div>IE (New)</div>\r\n     " +
"                   </a>\r\n                    </li>\r\n                </ul>\r\n     " +
"       </div>\r\n            <p>Sorry for the inconvenience!</p>\r\n        </div>\r\n" +
"    <![endif]-->\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 36347), Tuple.Create("\"", 36388)
            
            #line 673 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 36353), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 36353), false)
, Tuple.Create(Tuple.Create("", 36365), Tuple.Create("Content/Scripts/LVSA.js", 36365), true)
);

WriteLiteral("></script>\r\n\r\n    <!-- Javascript Libraries -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 36449), Tuple.Create("\"", 36544)
            
            #line 676 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 36455), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 36455), false)
, Tuple.Create(Tuple.Create("", 36467), Tuple.Create("Content/Templates/Material/vendors/bower_components/jquery/dist/jquery.min.js", 36467), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 36568), Tuple.Create("\"", 36672)
            
            #line 677 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 36574), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 36574), false)
, Tuple.Create(Tuple.Create("", 36586), Tuple.Create("Content/Templates/Material/vendors/bower_components/bootstrap/dist/js/bootstrap.m" +
"in.js", 36586), true)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 36698), Tuple.Create("\"", 36787)
            
            #line 679 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 36704), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 36704), false)
, Tuple.Create(Tuple.Create("", 36716), Tuple.Create("Content/Templates/Material/vendors/bower_components/flot/jquery.flot.js", 36716), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 36811), Tuple.Create("\"", 36907)
            
            #line 680 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 36817), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 36817), false)
, Tuple.Create(Tuple.Create("", 36829), Tuple.Create("Content/Templates/Material/vendors/bower_components/flot/jquery.flot.resize.js", 36829), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 36931), Tuple.Create("\"", 37032)
            
            #line 681 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 36937), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 36937), false)
, Tuple.Create(Tuple.Create("", 36949), Tuple.Create("Content/Templates/Material/vendors/bower_components/flot.curvedlines/curvedLines." +
"js", 36949), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 37056), Tuple.Create("\"", 37143)
            
            #line 682 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 37062), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 37062), false)
, Tuple.Create(Tuple.Create("", 37074), Tuple.Create("Content/Templates/Material/vendors/sparklines/jquery.sparkline.min.js", 37074), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 37167), Tuple.Create("\"", 37290)
            
            #line 683 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 37173), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 37173), false)
, Tuple.Create(Tuple.Create("", 37185), Tuple.Create("Content/Templates/Material/vendors/bower_components/jquery.easy-pie-chart/dist/jq" +
"uery.easypiechart.min.js", 37185), true)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 37316), Tuple.Create("\"", 37410)
            
            #line 685 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 37322), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 37322), false)
, Tuple.Create(Tuple.Create("", 37334), Tuple.Create("Content/Templates/Material/vendors/bower_components/moment/min/moment.min.js", 37334), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 37434), Tuple.Create("\"", 37542)
            
            #line 686 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 37440), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 37440), false)
, Tuple.Create(Tuple.Create("", 37452), Tuple.Create("Content/Templates/Material/vendors/bower_components/fullcalendar/dist/fullcalenda" +
"r.min.js", 37452), true)
, Tuple.Create(Tuple.Create(" ", 37541), Tuple.Create("", 37541), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 37566), Tuple.Create("\"", 37677)
            
            #line 687 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 37572), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 37572), false)
, Tuple.Create(Tuple.Create("", 37584), Tuple.Create("Content/Templates/Material/vendors/bower_components/simpleWeather/jquery.simpleWe" +
"ather.min.js", 37584), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 37701), Tuple.Create("\"", 37813)
            
            #line 688 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 37707), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 37707), false)
, Tuple.Create(Tuple.Create("", 37719), Tuple.Create("Content/Templates/Material/vendors/bower_components/jquery.nicescroll/jquery.nice" +
"scroll.min.js", 37719), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 37837), Tuple.Create("\"", 37930)
            
            #line 689 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 37843), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 37843), false)
, Tuple.Create(Tuple.Create("", 37855), Tuple.Create("Content/Templates/Material/vendors/bower_components/Waves/dist/waves.min.js", 37855), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 37954), Tuple.Create("\"", 38045)
            
            #line 690 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 37960), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 37960), false)
, Tuple.Create(Tuple.Create("", 37972), Tuple.Create("Content/Templates/Material/vendors/bootstrap-growl/bootstrap-growl.min.js", 37972), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 38069), Tuple.Create("\"", 38182)
            
            #line 691 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 38075), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 38075), false)
, Tuple.Create(Tuple.Create("", 38087), Tuple.Create("Content/Templates/Material/vendors/bower_components/bootstrap-sweetalert/lib/swee" +
"t-alert.min.js", 38087), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 38206), Tuple.Create("\"", 38290)
            
            #line 692 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 38212), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 38212), false)
, Tuple.Create(Tuple.Create("", 38224), Tuple.Create("Content/Templates/Material/vendors/bootgrid/jquery.bootgrid.min.js", 38224), true)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 38316), Tuple.Create("\"", 38381)
            
            #line 694 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 38322), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 38322), false)
, Tuple.Create(Tuple.Create("", 38334), Tuple.Create("Content/Plugins/SignalR/jquery.signalR-2.2.0.js", 38334), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 38405), Tuple.Create("\"", 38473)
            
            #line 695 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 38411), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 38411), false)
, Tuple.Create(Tuple.Create("", 38423), Tuple.Create("Content/Plugins/Unobtrusive/jquery.validate.min.js", 38423), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 38497), Tuple.Create("\"", 38577)
            
            #line 696 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 38503), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 38503), false)
, Tuple.Create(Tuple.Create("", 38515), Tuple.Create("Content/Plugins/Unobtrusive/jquery.validate.unobtrusive.min.js", 38515), true)
);

WriteLiteral("></script>\r\n\r\n    <!-- Placeholder for IE9 -->\r\n    <!--[if IE 9 ]>\r\n        <scr" +
"ipt src=\"");

            
            #line 700 "..\..\Views\Shared\_Layout3.cshtml"
                 Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral("Content/Templates/Material/vendors/bower_components/jquery-placeholder/jquery.pla" +
"ceholder.min.js\"></script>\r\n    <![endif]-->\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 38820), Tuple.Create("\"", 38900)
            
            #line 703 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 38826), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 38826), false)
, Tuple.Create(Tuple.Create("", 38838), Tuple.Create("Content/Templates/Material/js/flot-charts/curved-line-chart.js", 38838), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 38924), Tuple.Create("\"", 38997)
            
            #line 704 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 38930), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 38930), false)
, Tuple.Create(Tuple.Create("", 38942), Tuple.Create("Content/Templates/Material/js/flot-charts/line-chart.js", 38942), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 39021), Tuple.Create("\"", 39078)
            
            #line 705 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 39027), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 39027), false)
, Tuple.Create(Tuple.Create("", 39039), Tuple.Create("Content/Templates/Material/js/charts.js", 39039), true)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 39104), Tuple.Create("\"", 39161)
            
            #line 707 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 39110), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 39110), false)
, Tuple.Create(Tuple.Create("", 39122), Tuple.Create("Content/Templates/Material/js/charts.js", 39122), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 39185), Tuple.Create("\"", 39245)
            
            #line 708 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 39191), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 39191), false)
, Tuple.Create(Tuple.Create("", 39203), Tuple.Create("Content/Templates/Material/js/functions.js", 39203), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 39269), Tuple.Create("\"", 39324)
            
            #line 709 "..\..\Views\Shared\_Layout3.cshtml"
, Tuple.Create(Tuple.Create("", 39275), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 39275), false)
, Tuple.Create(Tuple.Create("", 39287), Tuple.Create("Content/Templates/Material/js/demo.js", 39287), true)
);

WriteLiteral("></script>\r\n\r\n    <script>\r\n        $(function () {\r\n            LVSA.CDN.Plugins" +
".Inicialize();\r\n\r\n        });\r\n    </script>\r\n\r\n");

WriteLiteral("    ");

            
            #line 718 "..\..\Views\Shared\_Layout3.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
