#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout2.cshtml")]
    public partial class _Views_Shared__Layout2_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout2_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_Layout2.cshtml"
  
    
    string serverCDN = System.Web.Configuration.WebConfigurationManager.AppSettings["Address_LVSA.CDN.Presentation"];

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<!--[if IE 9 ]><html class=\"ie9\"><![endif]-->\r\n<head" +
">\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(">\r\n    <title>");

            
            #line 13 "..\..\Views\Shared\_Layout2.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 438), Tuple.Create("\"", 503)
            
            #line 15 "..\..\Views\Shared\_Layout2.cshtml"
, Tuple.Create(Tuple.Create("", 445), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 445), false)
, Tuple.Create(Tuple.Create("", 457), Tuple.Create("Content/Templates/Ace/assets/css/bootstrap.css", 457), true)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 535), Tuple.Create("\"", 603)
            
            #line 16 "..\..\Views\Shared\_Layout2.cshtml"
, Tuple.Create(Tuple.Create("", 542), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 542), false)
, Tuple.Create(Tuple.Create("", 554), Tuple.Create("Content/Templates/Ace/assets/css/font-awesome.css", 554), true)
);

WriteLiteral(" />\r\n\r\n    <!-- Vendor CSS -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 645), Tuple.Create("\"", 743)
            
            #line 19 "..\..\Views\Shared\_Layout2.cshtml"
, Tuple.Create(Tuple.Create("", 652), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 652), false)
, Tuple.Create(Tuple.Create("", 664), Tuple.Create("Content/Templates/Material/vendors/bower_components/animate.css/animate.min.css", 664), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 773), Tuple.Create("\"", 916)
            
            #line 20 "..\..\Views\Shared\_Layout2.cshtml"
, Tuple.Create(Tuple.Create("", 780), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 780), false)
, Tuple.Create(Tuple.Create("", 792), Tuple.Create("Content/Templates/Material/vendors/bower_components/material-design-iconic-font/d" +
"ist/css/material-design-iconic-font.min.css", 792), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n\r\n    <!-- CSS -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 966), Tuple.Create("\"", 1029)
            
            #line 23 "..\..\Views\Shared\_Layout2.cshtml"
, Tuple.Create(Tuple.Create("", 973), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 973), false)
, Tuple.Create(Tuple.Create("", 985), Tuple.Create("Content/Templates/Material/css/app.min.1.css", 985), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1059), Tuple.Create("\"", 1122)
            
            #line 24 "..\..\Views\Shared\_Layout2.cshtml"
, Tuple.Create(Tuple.Create("", 1066), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1066), false)
, Tuple.Create(Tuple.Create("", 1078), Tuple.Create("Content/Templates/Material/css/app.min.2.css", 1078), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n</head>\r\n\r\n<body");

WriteLiteral(" class=\"login-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Views\Shared\_Layout2.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
    </div>

    <!-- Older IE warning message -->
    <!--[if lt IE 9]>
        <div class=""ie-warning"">
            <h1 class=""c-white"">Warning!!</h1>
            <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>
            <div class=""iew-container"">
                <ul class=""iew-download"">
                    <li>
                        <a href=""http://www.google.com/chrome/"">
                            <img src=""");

            
            #line 41 "..\..\Views\Shared\_Layout2.cshtml"
                                  Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral(@"Content/Templates/Material/img/browsers/chrome.png"" alt="""">
                            <div>Chrome</div>
                        </a>
                    </li>
                    <li>
                        <a href=""https://www.mozilla.org/en-US/firefox/new/"">
                            <img src=""");

            
            #line 47 "..\..\Views\Shared\_Layout2.cshtml"
                                  Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral(@"Content/Templates/Material/img/browsers/firefox.png"" alt="""">
                            <div>Firefox</div>
                        </a>
                    </li>
                    <li>
                        <a href=""http://www.opera.com"">
                            <img src=""");

            
            #line 53 "..\..\Views\Shared\_Layout2.cshtml"
                                  Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral(@"Content/Templates/Material/img/browsers/opera.png"" alt="""">
                            <div>Opera</div>
                        </a>
                    </li>
                    <li>
                        <a href=""https://www.apple.com/safari/"">
                            <img src=""");

            
            #line 59 "..\..\Views\Shared\_Layout2.cshtml"
                                  Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral(@"Content/Templates/Material/img/browsers/safari.png"" alt="""">
                            <div>Safari</div>
                        </a>
                    </li>
                    <li>
                        <a href=""http://windows.microsoft.com/en-us/internet-explorer/download-ie"">
                            <img src=""");

            
            #line 65 "..\..\Views\Shared\_Layout2.cshtml"
                                  Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral(@"Content/Templates/Material/img/browsers/ie.png"" alt="""">
                            <div>IE (New)</div>
                        </a>
                    </li>
                </ul>
            </div>
            <p>Sorry for the inconvenience!</p>
        </div>
    <![endif]-->

");

WriteLiteral("    ");

            
            #line 75 "..\..\Views\Shared\_Layout2.cshtml"
Write(RenderSection("footer", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("    ");

            
            #line 78 "..\..\Views\Shared\_Layout2.cshtml"
Write(Html.Partial("_PartialView/Loading"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n\r\n\r\n    <!-- Javascript Libraries -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3485), Tuple.Create("\"", 3580)
            
            #line 85 "..\..\Views\Shared\_Layout2.cshtml"
, Tuple.Create(Tuple.Create("", 3491), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 3491), false)
, Tuple.Create(Tuple.Create("", 3503), Tuple.Create("Content/Templates/Material/vendors/bower_components/jquery/dist/jquery.min.js", 3503), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3604), Tuple.Create("\"", 3708)
            
            #line 86 "..\..\Views\Shared\_Layout2.cshtml"
, Tuple.Create(Tuple.Create("", 3610), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 3610), false)
, Tuple.Create(Tuple.Create("", 3622), Tuple.Create("Content/Templates/Material/vendors/bower_components/bootstrap/dist/js/bootstrap.m" +
"in.js", 3622), true)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3734), Tuple.Create("\"", 3827)
            
            #line 88 "..\..\Views\Shared\_Layout2.cshtml"
, Tuple.Create(Tuple.Create("", 3740), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 3740), false)
, Tuple.Create(Tuple.Create("", 3752), Tuple.Create("Content/Templates/Material/vendors/bower_components/Waves/dist/waves.min.js", 3752), true)
);

WriteLiteral("></script>\r\n\r\n    <!-- Placeholder for IE9 -->\r\n    <!--[if IE 9 ]>\r\n        <scr" +
"ipt src=\"vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js\">" +
"</script>\r\n    <![endif]-->\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4031), Tuple.Create("\"", 4091)
            
            #line 95 "..\..\Views\Shared\_Layout2.cshtml"
, Tuple.Create(Tuple.Create("", 4037), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 4037), false)
, Tuple.Create(Tuple.Create("", 4049), Tuple.Create("Content/Templates/Material/js/functions.js", 4049), true)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4117), Tuple.Create("\"", 4158)
            
            #line 97 "..\..\Views\Shared\_Layout2.cshtml"
, Tuple.Create(Tuple.Create("", 4123), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 4123), false)
, Tuple.Create(Tuple.Create("", 4135), Tuple.Create("Content/Scripts/LVSA.js", 4135), true)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n\r\n            LVSA.CDN.Plugins.Inicialize();\r\n\r\n     " +
"   });\r\n    </script>\r\n\r\n");

WriteLiteral("    ");

            
            #line 107 "..\..\Views\Shared\_Layout2.cshtml"
Write(Html.Partial("_PartialView/Gritter"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 109 "..\..\Views\Shared\_Layout2.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</body>\r\n</html>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
