#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_Layout.cshtml"
  
    string serverCDN = System.Web.Configuration.WebConfigurationManager.AppSettings["Address_LVSA.CDN.Presentation"];


    LVSA.Security.Application.Models.Seguranca Seguranca = ((LVSA.Security.Application.Models.Seguranca)TempData["Seguranca"]);


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"pt-br\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge,chrome=1\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 14 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"overview &amp; stats\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\"");

WriteLiteral(" />\r\n\r\n    <link");

WriteLiteral(" rel=\'shortcut icon\'");

WriteLiteral(" type=\'image/x-icon\'");

WriteAttribute("href", Tuple.Create(" href=\'", 658), Tuple.Create("\'", 678)
, Tuple.Create(Tuple.Create("", 665), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 665), false)
);

WriteLiteral(" />\r\n\r\n    <!-- bootstrap & fontawesome -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 750), Tuple.Create("\"", 815)
            
            #line 22 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 757), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 757), false)
, Tuple.Create(Tuple.Create("", 769), Tuple.Create("Content/Templates/Ace/assets/css/bootstrap.css", 769), true)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 847), Tuple.Create("\"", 915)
            
            #line 23 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 854), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 854), false)
, Tuple.Create(Tuple.Create("", 866), Tuple.Create("Content/Templates/Ace/assets/css/font-awesome.css", 866), true)
);

WriteLiteral(" />\r\n\r\n    <!-- page specific plugin styles -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 991), Tuple.Create("\"", 1053)
            
            #line 26 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 998), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 998), false)
, Tuple.Create(Tuple.Create("", 1010), Tuple.Create("Content/Templates/Ace/assets/css/chosen.css", 1010), true)
);

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1068), Tuple.Create("\"", 1138)
            
            #line 27 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1075), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1075), false)
, Tuple.Create(Tuple.Create("", 1087), Tuple.Create("Content/Templates/Ace/assets/css/jquery.gritter.css", 1087), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1187), Tuple.Create("\"", 1253)
            
            #line 28 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1194), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1194), false)
, Tuple.Create(Tuple.Create("", 1206), Tuple.Create("Content/Templates/Ace/assets/css/datepicker.css", 1206), true)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1285), Tuple.Create("\"", 1365)
            
            #line 29 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1292), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1292), false)
, Tuple.Create(Tuple.Create("", 1304), Tuple.Create("Content/Templates/Ace/assets/css/bootstrap-datetimepicker.css", 1304), true)
);

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1380), Tuple.Create("\"", 1444)
            
            #line 30 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1387), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1387), false)
, Tuple.Create(Tuple.Create("", 1399), Tuple.Create("Content/Templates/Ace/assets/css/colorbox.css", 1399), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <!-- text fonts -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1520), Tuple.Create("\"", 1585)
            
            #line 33 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1527), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1527), false)
, Tuple.Create(Tuple.Create("", 1539), Tuple.Create("Content/Templates/Ace/assets/css/ace-fonts.css", 1539), true)
);

WriteLiteral(" />\r\n\r\n    <!-- ace styles -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1644), Tuple.Create("\"", 1703)
            
            #line 36 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1651), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1651), false)
, Tuple.Create(Tuple.Create("", 1663), Tuple.Create("Content/Templates/Ace/assets/css/ace.css", 1663), true)
);

WriteLiteral(" class=\"ace-main-stylesheet\"");

WriteLiteral(" id=\"main-ace-style\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1766), Tuple.Create("\"", 1831)
            
            #line 37 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1773), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1773), false)
, Tuple.Create(Tuple.Create("", 1785), Tuple.Create("Content/Templates/Ace/assets/css/ace-skins.css", 1785), true)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1880), Tuple.Create("\"", 1922)
            
            #line 38 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1887), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1887), false)
, Tuple.Create(Tuple.Create("", 1899), Tuple.Create("Content/Styles/LVSA.css", 1899), true)
);

WriteLiteral(" />\r\n\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("styles", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <!--[if lte IE 9]>\r\n        <link rel=\"stylesheet\" href=\"");

            
            #line 43 "..\..\Views\Shared\_Layout.cshtml"
                                 Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral("Content/Templates/Ace/assets/css/ace-part2.css\" class=\"ace-main-stylesheet\" />\r\n " +
"   <![endif]-->\r\n    <!--[if lte IE 9]>\r\n      <link rel=\"stylesheet\" href=\"");

            
            #line 46 "..\..\Views\Shared\_Layout.cshtml"
                               Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral("Content/Templates/Ace/assets/css/ace-ie.css\" />\r\n    <![endif]-->\r\n    <!-- inlin" +
"e styles related to this page -->\r\n    <!-- ace settings handler -->\r\n    <scrip" +
"t");

WriteAttribute("src", Tuple.Create(" src=\"", 2383), Tuple.Create("\"", 2445)
            
            #line 50 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2389), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 2389), false)
, Tuple.Create(Tuple.Create("", 2401), Tuple.Create("Content/Templates/Ace/assets/js/ace-extra.js", 2401), true)
);

WriteLiteral("></script>\r\n\r\n    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements" +
" and media queries -->\r\n    <!--[if lte IE 8]>\r\n    <script src=\"");

            
            #line 54 "..\..\Views\Shared\_Layout.cshtml"
             Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral("Content/Templates/Ace/assets/js/html5shiv.js\"></script>\r\n    <script src=\"");

            
            #line 55 "..\..\Views\Shared\_Layout.cshtml"
             Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral("Content/Templates/Ace/assets/js/respond.js\"></script>\r\n    <![endif]-->\r\n</head>\r" +
"\n\r\n");

            
            #line 59 "..\..\Views\Shared\_Layout.cshtml"
  
    string skin = Request.Cookies["ace_skin"] != null ? Request.Cookies["ace_skin"].Value : "no-skin";
    string compact = Request.Cookies["ace_compact"] != null && Request.Cookies["ace_compact"].Value == "true" ? "compact" : "";
    TempData["##TempHover"] = Request.Cookies["ace_hover"] != null && Request.Cookies["ace_hover"].Value == "true" ? "hover" : "";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<body");

WriteAttribute("class", Tuple.Create(" class=\"", 3153), Tuple.Create("\"", 3166)
            
            #line 65 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3161), Tuple.Create<System.Object, System.Int32>(skin
            
            #line default
            #line hidden
, 3161), false)
);

WriteLiteral(">\r\n    <!-- #section:basics/navbar.layout -->\r\n    <div");

WriteLiteral(" id=\"navbar\"");

WriteLiteral(" class=\"navbar navbar-default\"");

WriteLiteral(">\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            try { ace.settings.check(\'navbar\', \'fixed\') } catch (e) { }\r\n     " +
"   </script>\r\n\r\n        <div");

WriteLiteral(" class=\"navbar-container\"");

WriteLiteral(" id=\"navbar-container\"");

WriteLiteral(">\r\n            <!-- #section:basics/sidebar.mobile.toggle -->\r\n            ");

WriteLiteral("\r\n\r\n            <!-- /section:basics/sidebar.mobile.toggle -->\r\n            <div");

WriteLiteral(" class=\"navbar-header pull-left\"");

WriteLiteral(">\r\n                <!-- #section:basics/navbar.layout.brand -->\r\n                " +
"<a");

WriteAttribute("href", Tuple.Create(" href=\"", 4077), Tuple.Create("\"", 4112)
            
            #line 87 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4084), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 4084), false)
);

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(">\r\n                    <small>\r\n                        <!--<i class=\"fa fa-leaf\"" +
"></i>-->\r\n                        <img");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" style=\"width:90px;\"");

WriteAttribute("src", Tuple.Create(" src=\"", 4291), Tuple.Create("\"", 4345)
            
            #line 90 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4297), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 4297), false)
, Tuple.Create(Tuple.Create("", 4309), Tuple.Create("Content/Images/logo_ubec_laranja.png", 4309), true)
);

WriteLiteral(">\r\n                        <small");

WriteLiteral(" class=\"hidden-xs hidden-sm\"");

WriteLiteral(" style=\"margin-left:35px;\"");

WriteLiteral("><i");

WriteAttribute("class", Tuple.Create(" class=\"", 4436), Tuple.Create("\"", 4469)
            
            #line 91 "..\..\Views\Shared\_Layout.cshtml"
               , Tuple.Create(Tuple.Create("", 4444), Tuple.Create<System.Object, System.Int32>(Seguranca.Aplicacao.Icon
            
            #line default
            #line hidden
, 4444), false)
);

WriteLiteral("></i> &nbsp; ");

            
            #line 91 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                 Write(Seguranca.Aplicacao.Exibicao);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                        <small");

WriteLiteral(" class=\"hidden-lg hidden-md\"");

WriteLiteral(@"></small>
                    </small>
                </a>

                <!-- /section:basics/navbar.layout.brand -->
                <!-- #section:basics/navbar.toggle -->
                <!-- /section:basics/navbar.toggle -->
            </div>

            <!-- #section:basics/navbar.dropdown -->
            <div");

WriteLiteral(" class=\"navbar-buttons navbar-header pull-right\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"nav ace-nav\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"transparent\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"ace-icon fa fa-flag\"");

WriteLiteral("></i>\r\n                        </a>\r\n\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown" +
"-close\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"ace-icon fa fa-flag\"");

WriteLiteral("></i>\r\n                                Contexto atual\r\n                          " +
"  </li>\r\n\r\n                            <li");

WriteLiteral(" class=\"dropdown-content\"");

WriteLiteral(">\r\n                                <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-navbar\"");

WriteLiteral(">\r\n                                    <li>\r\n                                    " +
"    <a");

WriteLiteral(" href=\"#\"");

WriteAttribute("title", Tuple.Create(" title=\"", 5808), Tuple.Create("\"", 5840)
            
            #line 118 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 5816), Tuple.Create<System.Object, System.Int32>(Seguranca.Coligada.Nome
            
            #line default
            #line hidden
, 5816), false)
);

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral("><b>Coligada</b></span>\r\n                                                <span");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 122 "..\..\Views\Shared\_Layout.cshtml"
                                               Write(Seguranca.Coligada.Id);

            
            #line default
            #line hidden
WriteLiteral(@"
                                                </span>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a");

WriteLiteral(" href=\"#\"");

WriteAttribute("title", Tuple.Create(" title=\"", 6450), Tuple.Create("\"", 6480)
            
            #line 128 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 6458), Tuple.Create<System.Object, System.Int32>(Seguranca.Filial.Nome
            
            #line default
            #line hidden
, 6458), false)
);

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral("><b>Filial</b></span>\r\n                                                <span");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 132 "..\..\Views\Shared\_Layout.cshtml"
                                               Write(Seguranca.Filial.Id);

            
            #line default
            #line hidden
WriteLiteral(@"
                                                </span>
                                            </div>
                                        </a>
                                    </li>

                                    <li>
                                        ");

WriteLiteral("\r\n                                    </li>\r\n\r\n\r\n\r\n                              " +
"      ");

WriteLiteral("\r\n\r\n                                </ul>\r\n                            </li>\r\n\r\n " +
"                           <li");

WriteLiteral(" class=\"dropdown-footer\"");

WriteLiteral(">\r\n");

            
            #line 181 "..\..\Views\Shared\_Layout.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 181 "..\..\Views\Shared\_Layout.cshtml"
                                 if (Seguranca.Aplicacao.ParametroSet != null && Seguranca.Aplicacao.ParametroSet.Count() > 0)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 9818), Tuple.Create("\"", 9854)
            
            #line 183 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 9825), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Param")
            
            #line default
            #line hidden
, 9825), false)
);

WriteLiteral(">\r\n                                        Alterar parâmetros\r\n                  " +
"                  </a>\r\n");

            
            #line 186 "..\..\Views\Shared\_Layout.cshtml"
                                }
                                else if (Seguranca.FilialSet.Count() > 1)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 10143), Tuple.Create("\"", 10182)
            
            #line 189 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 10150), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Contexto")
            
            #line default
            #line hidden
, 10150), false)
);

WriteLiteral(">\r\n                                        Alterar contexto\r\n                    " +
"                </a>\r\n");

            
            #line 192 "..\..\Views\Shared\_Layout.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </li>\r\n\r\n                        </ul>\r\n             " +
"       </li>\r\n\r\n");

WriteLiteral("                    ");

            
            #line 198 "..\..\Views\Shared\_Layout.cshtml"
               Write(Html.Partial("_PartialView/Navbar"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                    <!-- #section:basics/navbar.user_menu -->\r\n              " +
"      <li");

WriteLiteral(" class=\"transparent\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(">\r\n\r\n");

            
            #line 204 "..\..\Views\Shared\_Layout.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 204 "..\..\Views\Shared\_Layout.cshtml"
                             if (Seguranca.Usuario.Avatar != null)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <img");

WriteLiteral(" class=\"nav-user-photo\"");

WriteLiteral(" style=\"width:40px;height:40px;\"");

WriteAttribute("src", Tuple.Create(" src=\"", 10864), Tuple.Create("\"", 10944)
, Tuple.Create(Tuple.Create("", 10870), Tuple.Create("data:image;base64,", 10870), true)
            
            #line 206 "..\..\Views\Shared\_Layout.cshtml"
                                  , Tuple.Create(Tuple.Create("", 10888), Tuple.Create<System.Object, System.Int32>(System.Convert.ToBase64String(Seguranca.Usuario.Avatar)
            
            #line default
            #line hidden
, 10888), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 10945), Tuple.Create("\"", 10988)
            
            #line 206 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                 , Tuple.Create(Tuple.Create("", 10951), Tuple.Create<System.Object, System.Int32>(Seguranca.Usuario.Nome.Split(' ')[0]
            
            #line default
            #line hidden
, 10951), false)
);

WriteLiteral(" />\r\n");

            
            #line 207 "..\..\Views\Shared\_Layout.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <img");

WriteLiteral(" class=\"nav-user-photo\"");

WriteLiteral(" style=\"width:40px;height:40px;\"");

WriteAttribute("src", Tuple.Create(" src=\"", 11181), Tuple.Create("\"", 11247)
            
            #line 210 "..\..\Views\Shared\_Layout.cshtml"
                 , Tuple.Create(Tuple.Create("", 11187), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 11187), false)
, Tuple.Create(Tuple.Create("", 11199), Tuple.Create("Content/Templates/Ace/assets/avatars/avatar2.png", 11199), true)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 11248), Tuple.Create("\"", 11291)
            
            #line 210 "..\..\Views\Shared\_Layout.cshtml"
                                                                                   , Tuple.Create(Tuple.Create("", 11254), Tuple.Create<System.Object, System.Int32>(Seguranca.Usuario.Nome.Split(' ')[0]
            
            #line default
            #line hidden
, 11254), false)
);

WriteLiteral(" />\r\n");

            
            #line 211 "..\..\Views\Shared\_Layout.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <span");

WriteLiteral(" class=\"user-info\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 213 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Seguranca.Usuario.Nome.Split(' ')[0]);

            
            #line default
            #line hidden
WriteLiteral(",\r\n                                <small>Você está no ");

            
            #line 214 "..\..\Views\Shared\_Layout.cshtml"
                                               Write(Seguranca.Aplicacao.Exibicao);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n\r\n                            </span>\r\n\r\n                            <i" +
"");

WriteLiteral(" class=\"ace-icon fa fa-caret-down\"");

WriteLiteral("></i>\r\n                        </a>\r\n\r\n                        <ul");

WriteLiteral(" class=\"user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-care" +
"t dropdown-close\"");

WriteLiteral(">\r\n\r\n                            <li");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

            
            #line 224 "..\..\Views\Shared\_Layout.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 224 "..\..\Views\Shared\_Layout.cshtml"
                                 if (Seguranca.Usuario.Avatar != null)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <img");

WriteLiteral(" style=\"width:80px;max-width:80px;margin:8px 0 0 0;border-radius:20px;border:2px " +
"solid #fff;\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 12113), Tuple.Create("\"", 12156)
            
            #line 226 "..\..\Views\Shared\_Layout.cshtml"
                                                          , Tuple.Create(Tuple.Create("", 12119), Tuple.Create<System.Object, System.Int32>(Seguranca.Usuario.Nome.Split(' ')[0]
            
            #line default
            #line hidden
, 12119), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 12157), Tuple.Create("\"", 12237)
, Tuple.Create(Tuple.Create("", 12163), Tuple.Create("data:image;base64,", 12163), true)
            
            #line 226 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                        , Tuple.Create(Tuple.Create("", 12181), Tuple.Create<System.Object, System.Int32>(System.Convert.ToBase64String(Seguranca.Usuario.Avatar)
            
            #line default
            #line hidden
, 12181), false)
);

WriteLiteral(" />\r\n");

            
            #line 227 "..\..\Views\Shared\_Layout.cshtml"

                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <img");

WriteLiteral(" style=\"width:80px;max-width:80px;margin:8px 0 0 0;border-radius:20px;border:2px " +
"solid #fff;\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 12486), Tuple.Create("\"", 12529)
            
            #line 231 "..\..\Views\Shared\_Layout.cshtml"
                                                          , Tuple.Create(Tuple.Create("", 12492), Tuple.Create<System.Object, System.Int32>(Seguranca.Usuario.Nome.Split(' ')[0]
            
            #line default
            #line hidden
, 12492), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 12530), Tuple.Create("\"", 12596)
            
            #line 231 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                       , Tuple.Create(Tuple.Create("", 12536), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 12536), false)
, Tuple.Create(Tuple.Create("", 12548), Tuple.Create("Content/Templates/Ace/assets/avatars/avatar2.png", 12548), true)
);

WriteLiteral(" />\r\n");

            
            #line 232 "..\..\Views\Shared\_Layout.cshtml"

                                }

            
            #line default
            #line hidden
WriteLiteral("                            </li>\r\n\r\n                            <div");

WriteLiteral(" class=\"space-6\"");

WriteLiteral("></div>\r\n\r\n                            <li>\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 12803), Tuple.Create("\"", 12841)
            
            #line 239 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 12810), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Profile")
            
            #line default
            #line hidden
, 12810), false)
);

WriteLiteral(" title=\"Alterar conta\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"ace-icon fa fa-user\"");

WriteLiteral("></i>\r\n                                    Alterar conta\r\n                       " +
"         </a>\r\n                            </li>\r\n\r\n                            " +
"<li>\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 13134), Tuple.Create("\"", 13168)
            
            #line 246 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 13141), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "App")
            
            #line default
            #line hidden
, 13141), false)
);

WriteLiteral(" title=\"Ver todos sistemas\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"ace-icon fa fa-th\"");

WriteLiteral("></i>\r\n                                    Outras aplicações\r\n                   " +
"             </a>\r\n                            </li>\r\n\r\n                        " +
"    <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n\r\n\r\n\r\n                            <li>\r\n                                <" +
"a");

WriteAttribute("href", Tuple.Create(" href=\"", 13529), Tuple.Create("\"", 13566)
            
            #line 257 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 13536), Tuple.Create<System.Object, System.Int32>(Url.Action("Logout", "Login")
            
            #line default
            #line hidden
, 13536), false)
);

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"ace-icon fa fa-sign-out\"");

WriteLiteral(@"></i>
                                    Sair
                                </a>
                            </li>
                        </ul>
                    </li>

                    <!-- /section:basics/navbar.user_menu -->
                </ul>
            </div>

            <!-- /section:basics/navbar.dropdown -->
        </div><!-- /.navbar-container -->
    </div>

    <!-- /section:basics/navbar.layout -->
    <div");

WriteLiteral(" class=\"main-container\"");

WriteLiteral(" id=\"main-container\"");

WriteLiteral(">\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            try { ace.settings.check(\'main-container\', \'fixed\') } catch (e) { " +
"}\r\n        </script>\r\n\r\n        <div");

WriteLiteral(" id=\"sidebar\"");

WriteLiteral(" class=\"sidebar      h-sidebar                navbar-collapse collapse\"");

WriteLiteral(">\r\n            <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                try { ace.settings.check(\'sidebar\', \'fixed\') } catch (e) { }\r\n" +
"            </script>\r\n\r\n            <div");

WriteLiteral(" class=\"sidebar-shortcuts\"");

WriteLiteral(" id=\"sidebar-shortcuts\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"sidebar-shortcuts-large\"");

WriteLiteral(" id=\"sidebar-shortcuts-large\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"ace-icon fa fa-signal\"");

WriteLiteral("></i>\r\n                    </button>\r\n\r\n                    <button");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"ace-icon fa fa-pencil\"");

WriteLiteral("></i>\r\n                    </button>\r\n\r\n                    <!-- #section:basics/" +
"sidebar.layout.shortcuts -->\r\n                    <button");

WriteLiteral(" class=\"btn btn-warning\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"ace-icon fa fa-users\"");

WriteLiteral("></i>\r\n                    </button>\r\n\r\n                    <button");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"ace-icon fa fa-cogs\"");

WriteLiteral("></i>\r\n                    </button>\r\n\r\n                    <!-- /section:basics/" +
"sidebar.layout.shortcuts -->\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"sidebar-shortcuts-mini\"");

WriteLiteral(" id=\"sidebar-shortcuts-mini\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral("></span>\r\n\r\n                    <span");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral("></span>\r\n\r\n                    <span");

WriteLiteral(" class=\"btn btn-warning\"");

WriteLiteral("></span>\r\n\r\n                    <span");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral("></span>\r\n                </div>\r\n            </div><!-- /.sidebar-shortcuts -->\r" +
"\n\r\n            <ul");

WriteLiteral(" class=\"nav nav-list\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                ");

            
            #line 319 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Partial("_PartialView/Sidebar"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 321 "..\..\Views\Shared\_Layout.cshtml"
                
            
            #line default
            #line hidden
            
            #line 321 "..\..\Views\Shared\_Layout.cshtml"
                 if (Seguranca.RecursoSet != null)
                {
                    
            
            #line default
            #line hidden
            
            #line 323 "..\..\Views\Shared\_Layout.cshtml"
               Write(Html.Partial("_PartialView/Recursos", Seguranca.RecursoSet.Where(w => w.TipoRecurso.Codigo == "MN" && w.RecursoPaiId == null).OrderByDescending(o => o.Peso)));

            
            #line default
            #line hidden
            
            #line 323 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                                                                  
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </ul><!-- /.nav-list -->\r\n            <!-- #section:basics/sidebar." +
"layout.minimize -->\r\n            <!-- /section:basics/sidebar.layout.minimize --" +
">\r\n            <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                try { ace.settings.check(\'sidebar\', \'collapsed\') } catch (e) {" +
" }\r\n            </script>\r\n        </div>\r\n\r\n\r\n\r\n        <!-- /section:basics/si" +
"debar -->\r\n        <div");

WriteLiteral(" class=\"main-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"main-content-inner\"");

WriteLiteral(">\r\n                <!-- #section:basics/content.breadcrumbs -->\r\n                " +
"<div");

WriteLiteral(" class=\"breadcrumbs\"");

WriteLiteral(" id=\"breadcrumbs\"");

WriteLiteral(">\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                        try { ace.settings.check(\'breadcrumbs\', \'fixed\') } cat" +
"ch (e) { }\r\n                    </script>\r\n\r\n                    <ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 346 "..\..\Views\Shared\_Layout.cshtml"
                   Write(Html.Partial("_PartialView/Atalhos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </ul><!-- /.breadcrumb -->\r\n");

            
            #line 348 "..\..\Views\Shared\_Layout.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 348 "..\..\Views\Shared\_Layout.cshtml"
                     if (TempData["LVSA.Base.Infrastructure.Data.DbContexts.Ambiente"] != null && ((char)TempData["LVSA.Base.Infrastructure.Data.DbContexts.Ambiente"]) != default(char) && ((char)TempData["LVSA.Base.Infrastructure.Data.DbContexts.Ambiente"]) != 'P')
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <span");

WriteLiteral(" class=\"red\"");

WriteLiteral(">\r\n                            <big");

WriteLiteral(" class=\"hidden-sm hidden-xs\"");

WriteLiteral(">Atenção!</big> Ambiente de\r\n                            <b>\r\n");

WriteLiteral("                                ");

            
            #line 353 "..\..\Views\Shared\_Layout.cshtml"
                            Write(((char)TempData["LVSA.Base.Infrastructure.Data.DbContexts.Ambiente"]) == 'H' ? "homologação" : "");

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 354 "..\..\Views\Shared\_Layout.cshtml"
                            Write(((char)TempData["LVSA.Base.Infrastructure.Data.DbContexts.Ambiente"]) == 'D' ? "desenvolvimento" : "");

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa fa-code\"");

WriteLiteral("></i>\r\n                            </b>\r\n                        </span>\r\n");

            
            #line 358 "..\..\Views\Shared\_Layout.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <!-- #section:basics/content.searchbox -->\r\n                 " +
"   <div");

WriteLiteral(" class=\"nav-search\"");

WriteLiteral(" id=\"nav-search\"");

WriteLiteral(">\r\n");

            
            #line 361 "..\..\Views\Shared\_Layout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 361 "..\..\Views\Shared\_Layout.cshtml"
                         using (Html.BeginForm("Index", "Pesquisa", FormMethod.Post, new { @class = "form-search" }))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <span");

WriteLiteral(" class=\"input-icon\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Pesquisa\"");

WriteLiteral(" placeholder=\"Procurar\"");

WriteLiteral(" class=\"nav-search-input\"");

WriteLiteral(" id=\"nav-search-input\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n                                <i");

WriteLiteral(" class=\"ace-icon fa fa-search nav-search-icon\"");

WriteLiteral("></i>\r\n                            </span>\r\n");

            
            #line 367 "..\..\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div><!-- /.nav-search -->\r\n                    <!-- /sectio" +
"n:basics/content.searchbox -->\r\n                </div>\r\n                <!-- /se" +
"ction:basics/content.breadcrumbs -->\r\n                <div");

WriteLiteral(" class=\"page-content\"");

WriteLiteral(">\r\n                    <!-- #section:settings.box -->\r\n                    <div");

WriteLiteral(" class=\"ace-settings-container\"");

WriteLiteral(" id=\"ace-settings-container\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"btn btn-app btn-xs btn-warning ace-settings-btn\"");

WriteLiteral(" id=\"ace-settings-btn\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"ace-icon fa fa-cog bigger-130\"");

WriteLiteral("></i>\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"ace-settings-box clearfix\"");

WriteLiteral(" id=\"ace-settings-box\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"pull-left width-50\"");

WriteLiteral(">\r\n                                <!-- #section:settings.skins -->\r\n            " +
"                    <div");

WriteLiteral(" class=\"ace-settings-item\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" id=\"skin-colorpicker\"");

WriteLiteral(" class=\"hide\"");

WriteLiteral(">\r\n                                            ");

WriteLiteral("\r\n                                            <option");

WriteLiteral(" data-skin=\"no-skin\"");

WriteLiteral(" ");

            
            #line 389 "..\..\Views\Shared\_Layout.cshtml"
                                                                    Write(skin == "no-skin" ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(" value=\"#438EB9\">#438EB9</option>\r\n                                            <o" +
"ption");

WriteLiteral(" data-skin=\"skin-1\"");

WriteLiteral(" ");

            
            #line 390 "..\..\Views\Shared\_Layout.cshtml"
                                                                   Write(skin == "skin-1" ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(" value=\"#222A2D\">#222A2D</option>\r\n                                            <o" +
"ption");

WriteLiteral(" data-skin=\"skin-2\"");

WriteLiteral(" ");

            
            #line 391 "..\..\Views\Shared\_Layout.cshtml"
                                                                   Write(skin == "skin-2" ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(" value=\"#C6487E\">#C6487E</option>\r\n                                            ");

WriteLiteral(@"
                                        </select>
                                    </div>
                                    <span>&nbsp; Mudar tema</span>
                                </div>

                                <!-- /section:settings.skins -->
                                <!-- #section:settings.navbar -->
                                <div");

WriteLiteral(" class=\"ace-settings-item\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"ace ace-checkbox-2\"");

WriteLiteral(" id=\"ace-settings-navbar\"");

WriteLiteral(" />\r\n                                    <label");

WriteLiteral(" class=\"lbl\"");

WriteLiteral(" for=\"ace-settings-navbar\"");

WriteLiteral("> Fixar cabeçalho</label>\r\n                                </div>\r\n\r\n            " +
"                    <!-- /section:settings.navbar -->\r\n                         " +
"       <!-- #section:settings.sidebar -->\r\n                                <div");

WriteLiteral(" class=\"ace-settings-item\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"ace ace-checkbox-2\"");

WriteLiteral(" id=\"ace-settings-sidebar\"");

WriteLiteral(" />\r\n                                    <label");

WriteLiteral(" class=\"lbl\"");

WriteLiteral(" for=\"ace-settings-sidebar\"");

WriteLiteral("> Fixar menu</label>\r\n                                </div>\r\n\r\n                 " +
"               <!-- /section:settings.sidebar -->\r\n                             " +
"   <!-- #section:settings.breadcrumbs -->\r\n                                <div");

WriteLiteral(" class=\"ace-settings-item\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"ace ace-checkbox-2\"");

WriteLiteral(" id=\"ace-settings-breadcrumbs\"");

WriteLiteral(" />\r\n                                    <label");

WriteLiteral(" class=\"lbl\"");

WriteLiteral(" for=\"ace-settings-breadcrumbs\"");

WriteLiteral("> Fixar pesquisa</label>\r\n                                </div>\r\n\r\n             " +
"                   <!-- /section:settings.breadcrumbs -->\r\n                     " +
"           <!-- #section:settings.rtl -->\r\n                                ");

WriteLiteral("\r\n\r\n                                <!-- /section:settings.rtl -->\r\n             " +
"                   <!-- #section:settings.container -->\r\n                       " +
"         <div");

WriteLiteral(" class=\"ace-settings-item\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"ace ace-checkbox-2\"");

WriteLiteral(" id=\"ace-settings-add-container\"");

WriteLiteral(" />\r\n                                    <label");

WriteLiteral(" class=\"lbl\"");

WriteLiteral(" for=\"ace-settings-add-container\"");

WriteLiteral(@">
                                        Visualizar em
                                        <b>caixa</b>
                                    </label>
                                </div>

                                <!-- /section:settings.container -->
                            </div><!-- /.pull-left -->

                            <div");

WriteLiteral(" class=\"pull-left width-50\"");

WriteLiteral(">\r\n                                <!-- #section:basics/sidebar.options -->\r\n    " +
"                            <div");

WriteLiteral(" class=\"ace-settings-item\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" ");

            
            #line 442 "..\..\Views\Shared\_Layout.cshtml"
                                                       Write(TempData["##TempHover"] == "hover" ? "checked" : "");

            
            #line default
            #line hidden
WriteLiteral(" class=\"ace ace-checkbox-2\" id=\"ace-settings-hover\" />\r\n                         " +
"           <label");

WriteLiteral(" class=\"lbl\"");

WriteLiteral(" for=\"ace-settings-hover\"");

WriteLiteral("> Submenu ao sobrepor</label>\r\n                                </div>\r\n\r\n        " +
"                        <div");

WriteLiteral(" class=\"ace-settings-item\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" ");

            
            #line 447 "..\..\Views\Shared\_Layout.cshtml"
                                                       Write(compact == "compact" ? "checked" : "");

            
            #line default
            #line hidden
WriteLiteral(" class=\"ace ace-checkbox-2\" id=\"ace-settings-compact\" />\r\n                       " +
"             <label");

WriteLiteral(" class=\"lbl\"");

WriteLiteral(" for=\"ace-settings-compact\"");

WriteLiteral("> Menu compacto</label>\r\n                                </div>\r\n\r\n              " +
"                  ");

WriteLiteral(@"

                                <!-- /section:basics/sidebar.options -->
                            </div><!-- /.pull-left -->
                        </div><!-- /.ace-settings-box -->
                    </div><!-- /.ace-settings-container -->
                    <!-- /section:settings.box -->
                    <div");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(">\r\n                        <h1>\r\n");

WriteLiteral("                            ");

            
            #line 463 "..\..\Views\Shared\_Layout.cshtml"
                       Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <small>\r\n                                <i");

WriteLiteral(" class=\"ace-icon fa fa-angle-double-right\"");

WriteLiteral("></i>\r\n");

WriteLiteral("                                ");

            
            #line 466 "..\..\Views\Shared\_Layout.cshtml"
                           Write(ViewBag.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </small>\r\n                        </h1>\r\n          " +
"          </div><!-- /.page-header -->\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n\r\n");

            
            #line 473 "..\..\Views\Shared\_Layout.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 473 "..\..\Views\Shared\_Layout.cshtml"
                             if (TempData["LVSA.Base.Presentation#Shortcut"] != null && ((Dictionary<string, KeyValuePair<string, string>>)TempData["LVSA.Base.Presentation#Shortcut"]).Count() > 0)
                            {
                                foreach (var x in (Dictionary<string, KeyValuePair<string, string>>)TempData["LVSA.Base.Presentation#Shortcut"])
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 25994), Tuple.Create("\"", 26015)
            
            #line 477 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 26001), Tuple.Create<System.Object, System.Int32>(x.Value.Value
            
            #line default
            #line hidden
, 26001), false)
);

WriteLiteral(" class=\"btn btn-sm btn-link\"");

WriteLiteral("><i");

WriteAttribute("class", Tuple.Create(" class=\"", 26047), Tuple.Create("\"", 26067)
            
            #line 477 "..\..\Views\Shared\_Layout.cshtml"
                  , Tuple.Create(Tuple.Create("", 26055), Tuple.Create<System.Object, System.Int32>(x.Value.Key
            
            #line default
            #line hidden
, 26055), false)
);

WriteLiteral("></i> ");

            
            #line 477 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                 Write(x.Key);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 478 "..\..\Views\Shared\_Layout.cshtml"
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        </div>\r\n                    </div>\r\n                 " +
"   <br />\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                            <!-- PAGE CONTENT BEGINS -->\r\n                    " +
"        <div");

WriteLiteral(" class=\"hidden\"");

WriteLiteral(">\r\n                                <button");

WriteLiteral(" data-target=\"#sidebar2\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"pull-left menu-toggler navbar-toggle\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle sidebar</span>\r\n\r\n                                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n\r\n                                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n\r\n                                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                                </button>\r\n\r\n                          " +
"      <div");

WriteLiteral(" id=\"sidebar2\"");

WriteLiteral(" class=\"sidebar responsive hidden-lg hidden-md\"");

WriteLiteral(">\r\n                                    <ul");

WriteLiteral(" class=\"nav nav-list\"");

WriteLiteral(">\r\n");

            
            #line 501 "..\..\Views\Shared\_Layout.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 501 "..\..\Views\Shared\_Layout.cshtml"
                                         if (Seguranca.RecursoSet != null)
                                        {
                                            
            
            #line default
            #line hidden
            
            #line 503 "..\..\Views\Shared\_Layout.cshtml"
                                       Write(Html.Partial("_PartialView/Recursos", Seguranca.RecursoSet.Where(w => w.TipoRecurso.Codigo == "MN" && w.RecursoPaiId == null).OrderByDescending(o => o.Peso)));

            
            #line default
            #line hidden
            
            #line 503 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                                                                                          
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </ul><!-- /.nav-list -->\r\n\r\n                 " +
"                   <div");

WriteLiteral(" class=\"sidebar-toggle sidebar-collapse\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"ace-icon fa fa-angle-double-left\"");

WriteLiteral(" data-icon1=\"ace-icon fa fa-angle-double-left\"");

WriteLiteral(" data-icon2=\"ace-icon fa fa-angle-double-right\"");

WriteLiteral("></i>\r\n                                    </div>\r\n                              " +
"  </div><!-- .sidebar -->\r\n                            </div>\r\n                 " +
"           <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 513 "..\..\Views\Shared\_Layout.cshtml"
                           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
                            </div>

                            <!-- PAGE CONTENT ENDS -->
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.page-content -->
            </div>
        </div><!-- /.main-content -->
");

WriteLiteral("        ");

            
            #line 522 "..\..\Views\Shared\_Layout.cshtml"
   Write(Html.Partial("_PartialView/Loading"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n        <div");

WriteLiteral(" class=\"footer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"footer-inner\"");

WriteLiteral(">\r\n                <!-- #section:basics/footer -->\r\n                <div");

WriteLiteral(" class=\"footer-content\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"smaller-90\"");

WriteLiteral(">\r\n                        © ");

            
            #line 530 "..\..\Views\Shared\_Layout.cshtml"
                     Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 530 "..\..\Views\Shared\_Layout.cshtml"
                                          Write(Seguranca.Aplicacao.Exibicao);

            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("@ Leonelleo\r\n                    </span>\r\n                </div>\r\n\r\n             " +
"   <!-- /section:basics/footer -->\r\n            </div>\r\n        </div>\r\n\r\n      " +
"  <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"btn-scroll-up\"");

WriteLiteral(" class=\"btn-scroll-up btn btn-sm btn-inverse\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"ace-icon fa fa-angle-double-up icon-only bigger-110\"");

WriteLiteral("></i>\r\n        </a>\r\n    </div><!-- /.main-container -->\r\n    <!-- basic scripts " +
"-->\r\n    <!--[if !IE]> -->\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        window.jQuery || document.write(\"<script src=\'");

            
            #line 545 "..\..\Views\Shared\_Layout.cshtml"
                                                  Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral("Content/Templates/Ace/assets/js/jquery.js\'>\" + \"<\" + \"/script>\");\r\n    </script>\r" +
"\n\r\n    <!-- <![endif]-->\r\n    <!--[if IE]>\r\n    <script type=\"text/javascript\">\r" +
"\n     window.jQuery || document.write(\"<script src=\'");

            
            #line 551 "..\..\Views\Shared\_Layout.cshtml"
                                               Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral("Content/Templates/Ace/assets/js/jquery1x.js\'>\"+\"<\"+\"/script>\");\r\n    </script>\r\n " +
"   <![endif]-->\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        if (\'ontouchstart\' in document.documentElement) document.write(\"<scrip" +
"t src=\'");

            
            #line 555 "..\..\Views\Shared\_Layout.cshtml"
                                                                                 Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral("Content/Templates/Ace/assets/js/jquery.mobile.custom.js\'>\" + \"<\" + \"/script>\");\r\n" +
"    </script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 29708), Tuple.Create("\"", 29770)
            
            #line 557 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 29714), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 29714), false)
, Tuple.Create(Tuple.Create("", 29726), Tuple.Create("Content/Templates/Ace/assets/js/bootstrap.js", 29726), true)
);

WriteLiteral("></script>\r\n\r\n    <!-- page specific plugin scripts -->\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 29841), Tuple.Create("\"", 29882)
            
            #line 561 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 29847), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 29847), false)
, Tuple.Create(Tuple.Create("", 29859), Tuple.Create("Content/Scripts/LVSA.js", 29859), true)
);

WriteLiteral("></script>\r\n\r\n\r\n\r\n\r\n    <!--[if lte IE 8]>\r\n      <script src=\"");

            
            #line 567 "..\..\Views\Shared\_Layout.cshtml"
               Write(serverCDN);

            
            #line default
            #line hidden
WriteLiteral("Content/Templates/Ace/assets/js/excanvas.js\"></script>\r\n    <![endif]-->\r\n    <sc" +
"ript");

WriteAttribute("src", Tuple.Create(" src=\"", 30043), Tuple.Create("\"", 30112)
            
            #line 569 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 30049), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 30049), false)
, Tuple.Create(Tuple.Create("", 30061), Tuple.Create("Content/Templates/Ace/assets/js/jquery-ui.custom.js", 30061), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 30136), Tuple.Create("\"", 30210)
            
            #line 570 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 30142), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 30142), false)
, Tuple.Create(Tuple.Create("", 30154), Tuple.Create("Content/Templates/Ace/assets/js/jquery.ui.touch-punch.js", 30154), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 30234), Tuple.Create("\"", 30306)
            
            #line 571 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 30240), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 30240), false)
, Tuple.Create(Tuple.Create("", 30252), Tuple.Create("Content/Templates/Ace/assets/js/jquery.easypiechart.js", 30252), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 30330), Tuple.Create("\"", 30399)
            
            #line 572 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 30336), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 30336), false)
, Tuple.Create(Tuple.Create("", 30348), Tuple.Create("Content/Templates/Ace/assets/js/jquery.sparkline.js", 30348), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 30423), Tuple.Create("\"", 30492)
            
            #line 573 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 30429), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 30429), false)
, Tuple.Create(Tuple.Create("", 30441), Tuple.Create("Content/Templates/Ace/assets/js/flot/jquery.flot.js", 30441), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 30516), Tuple.Create("\"", 30589)
            
            #line 574 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 30522), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 30522), false)
, Tuple.Create(Tuple.Create("", 30534), Tuple.Create("Content/Templates/Ace/assets/js/flot/jquery.flot.pie.js", 30534), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 30613), Tuple.Create("\"", 30689)
            
            #line 575 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 30619), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 30619), false)
, Tuple.Create(Tuple.Create("", 30631), Tuple.Create("Content/Templates/Ace/assets/js/flot/jquery.flot.resize.js", 30631), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 30713), Tuple.Create("\"", 30780)
            
            #line 576 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 30719), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 30719), false)
, Tuple.Create(Tuple.Create("", 30731), Tuple.Create("Content/Templates/Ace/assets/js/jquery.gritter.js", 30731), true)
);

WriteLiteral("></script>\r\n\r\n    <!-- ace scripts -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 30832), Tuple.Create("\"", 30906)
            
            #line 579 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 30838), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 30838), false)
, Tuple.Create(Tuple.Create("", 30850), Tuple.Create("Content/Templates/Ace/assets/js/ace/elements.scroller.js", 30850), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 30930), Tuple.Create("\"", 31007)
            
            #line 580 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 30936), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 30936), false)
, Tuple.Create(Tuple.Create("", 30948), Tuple.Create("Content/Templates/Ace/assets/js/ace/elements.colorpicker.js", 30948), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31031), Tuple.Create("\"", 31106)
            
            #line 581 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 31037), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 31037), false)
, Tuple.Create(Tuple.Create("", 31049), Tuple.Create("Content/Templates/Ace/assets/js/ace/elements.fileinput.js", 31049), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31130), Tuple.Create("\"", 31205)
            
            #line 582 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 31136), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 31136), false)
, Tuple.Create(Tuple.Create("", 31148), Tuple.Create("Content/Templates/Ace/assets/js/ace/elements.typeahead.js", 31148), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31229), Tuple.Create("\"", 31302)
            
            #line 583 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 31235), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 31235), false)
, Tuple.Create(Tuple.Create("", 31247), Tuple.Create("Content/Templates/Ace/assets/js/ace/elements.wysiwyg.js", 31247), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31326), Tuple.Create("\"", 31399)
            
            #line 584 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 31332), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 31332), false)
, Tuple.Create(Tuple.Create("", 31344), Tuple.Create("Content/Templates/Ace/assets/js/ace/elements.spinner.js", 31344), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31423), Tuple.Create("\"", 31497)
            
            #line 585 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 31429), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 31429), false)
, Tuple.Create(Tuple.Create("", 31441), Tuple.Create("Content/Templates/Ace/assets/js/ace/elements.treeview.js", 31441), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31521), Tuple.Create("\"", 31593)
            
            #line 586 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 31527), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 31527), false)
, Tuple.Create(Tuple.Create("", 31539), Tuple.Create("Content/Templates/Ace/assets/js/ace/elements.wizard.js", 31539), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31617), Tuple.Create("\"", 31688)
            
            #line 587 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 31623), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 31623), false)
, Tuple.Create(Tuple.Create("", 31635), Tuple.Create("Content/Templates/Ace/assets/js/ace/elements.aside.js", 31635), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31712), Tuple.Create("\"", 31772)
            
            #line 588 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 31718), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 31718), false)
, Tuple.Create(Tuple.Create("", 31730), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.js", 31730), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31796), Tuple.Create("\"", 31869)
            
            #line 589 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 31802), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 31802), false)
, Tuple.Create(Tuple.Create("", 31814), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.ajax-content.js", 31814), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31893), Tuple.Create("\"", 31964)
            
            #line 590 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 31899), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 31899), false)
, Tuple.Create(Tuple.Create("", 31911), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.touch-drag.js", 31911), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31988), Tuple.Create("\"", 32056)
            
            #line 591 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 31994), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 31994), false)
, Tuple.Create(Tuple.Create("", 32006), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.sidebar.js", 32006), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32080), Tuple.Create("\"", 32157)
            
            #line 592 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 32086), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 32086), false)
, Tuple.Create(Tuple.Create("", 32098), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.sidebar-scroll-1.js", 32098), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32181), Tuple.Create("\"", 32255)
            
            #line 593 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 32187), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 32187), false)
, Tuple.Create(Tuple.Create("", 32199), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.submenu-hover.js", 32199), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32279), Tuple.Create("\"", 32350)
            
            #line 594 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 32285), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 32285), false)
, Tuple.Create(Tuple.Create("", 32297), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.widget-box.js", 32297), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32374), Tuple.Create("\"", 32443)
            
            #line 595 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 32380), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 32380), false)
, Tuple.Create(Tuple.Create("", 32392), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.settings.js", 32392), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32467), Tuple.Create("\"", 32540)
            
            #line 596 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 32473), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 32473), false)
, Tuple.Create(Tuple.Create("", 32485), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.settings-rtl.js", 32485), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32564), Tuple.Create("\"", 32638)
            
            #line 597 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 32570), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 32570), false)
, Tuple.Create(Tuple.Create("", 32582), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.settings-skin.js", 32582), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32662), Tuple.Create("\"", 32739)
            
            #line 598 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 32668), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 32668), false)
, Tuple.Create(Tuple.Create("", 32680), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.widget-on-reload.js", 32680), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32763), Tuple.Create("\"", 32846)
            
            #line 599 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 32769), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 32769), false)
, Tuple.Create(Tuple.Create("", 32781), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.searchbox-autocomplete.js", 32781), true)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32872), Tuple.Create("\"", 32937)
            
            #line 601 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 32878), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 32878), false)
, Tuple.Create(Tuple.Create("", 32890), Tuple.Create("Content/Plugins/SignalR/jquery.signalR-2.2.0.js", 32890), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32961), Tuple.Create("\"", 33029)
            
            #line 602 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 32967), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 32967), false)
, Tuple.Create(Tuple.Create("", 32979), Tuple.Create("Content/Plugins/Unobtrusive/jquery.validate.min.js", 32979), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 33053), Tuple.Create("\"", 33133)
            
            #line 603 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 33059), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 33059), false)
, Tuple.Create(Tuple.Create("", 33071), Tuple.Create("Content/Plugins/Unobtrusive/jquery.validate.unobtrusive.min.js", 33071), true)
);

WriteLiteral("></script>\r\n\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function ($) {
            $('#sidebar2').insertBefore('.page-content').ace_sidebar('collapse', false);
            //$('#navbar').addClass('h-navbar');
            //$('.footer').insertAfter('.page-content');

            $('.page-content').addClass('main-content');

            $('.menu-toggler[data-target=""#sidebar2""]').insertBefore('.navbar-brand');


            $(document).on('settings.ace.two_menu', function (e, event_name, event_val) {
                if (event_name == 'sidebar_fixed') {
                    if ($('#sidebar').hasClass('sidebar-fixed')) $('#sidebar2').addClass('sidebar-fixed')
                    else $('#sidebar2').removeClass('sidebar-fixed')
                }
            }).triggerHandler('settings.ace.two_menu', ['sidebar_fixed', $('#sidebar').hasClass('sidebar-fixed')]);

            $('#sidebar2[data-sidebar-hover=true]').ace_sidebar_hover('reset');
            $('#sidebar2[data-sidebar-scroll=true]').ace_sidebar_scroll('reset', true);
        })
    </script>

    <!-- inline scripts related to this page -->
    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n        var lgritterhub = null;\r\n        var ggritterhub = null;\r\n        va" +
"r gconnection = null;\r\n\r\n        jQuery(function ($) {\r\n\r\n            ");

WriteLiteral("\r\n            ");

WriteLiteral("\r\n\r\n            ");

WriteLiteral("\r\n            ");

WriteLiteral(@"

            //var information = function (title, message) {
            //    LVSA.CDN.Plugins.Gritter.Information(title, message);
            //};

            //var answer = function (title, message, answer) {
            //    LVSA.CDN.Plugins.Gritter.Answer(title, message, false, answer);
            //};

            ");

WriteLiteral("\r\n\r\n            var loading = function (message) {\r\n                UBEC.Utility." +
"Loading(true, message);\r\n            }\r\n\r\n            var hide = function () {\r\n" +
"                UBEC.Utility.Loading(false);\r\n            }\r\n\r\n            //lgr" +
"itterhub = lconnection.createHubProxy(\'GritterHub\');\r\n            //lloadinghub " +
"= lconnection.createHubProxy(\'LoadingHub\');\r\n            //ggritterhub = gconnec" +
"tion.createHubProxy(\'GritterHub\');\r\n\r\n            //lgritterhub.on(\'Information\'" +
", information);\r\n            //lgritterhub.on(\'Answer\', answer);\r\n            //" +
"lgritterhub.on(\'Ask\', ask);\r\n\r\n            //lloadinghub.on(\'Loading\', loading);" +
"\r\n            //lloadinghub.on(\'Hide\', hide);\r\n\r\n            //ggritterhub.on(\'I" +
"nformation\', information);\r\n            //ggritterhub.on(\'Answer\', answer);\r\n   " +
"         //ggritterhub.on(\'Ask\', ask);\r\n\r\n            //lconnection.start().done" +
"(function () {\r\n            //    console.log(\'Comunicação local estabelecida..." +
"\');\r\n            //});\r\n\r\n            //gconnection.start().done(function () {\r\n" +
"            //    console.log(\'Comunicação global estabelecida...\');\r\n          " +
"  //});\r\n\r\n            LVSA.CDN.Plugins.Inicialize();\r\n\r\n\r\n\r\n            $(\'#sid" +
"ebar li.active\').parents(\'ul.submenu\').show();\r\n            $(\'#sidebar ul.open\'" +
").parents(\'ul.submenu\').show();\r\n            $(\'#sidebar li.active\').parents(\'ul" +
".submenu\').parent(\'li\').addClass(\'open\');\r\n            $(\'#sidebar ul.open\').par" +
"ents(\'ul.submenu\').parents(\'li\').addClass(\'open\');\r\n\r\n        });\r\n    </script>" +
"\r\n\r\n    <!-- the following scripts are used in demo only for onpage help and you" +
" don\'t need them -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 37460), Tuple.Create("\"", 37531)
            
            #line 703 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 37467), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 37467), false)
, Tuple.Create(Tuple.Create("", 37479), Tuple.Create("Content/Templates/Ace/assets/css/ace.onpage-help.css", 37479), true)
);

WriteLiteral(" />\r\n    ");

WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("> ace.vars[\'base\'] = \'..\'; </script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 37702), Tuple.Create("\"", 37779)
            
            #line 707 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 37708), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 37708), false)
, Tuple.Create(Tuple.Create("", 37720), Tuple.Create("Content/Templates/Ace/assets/js/ace/elements.onpage-help.js", 37720), true)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 37803), Tuple.Create("\"", 37875)
            
            #line 708 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 37809), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 37809), false)
, Tuple.Create(Tuple.Create("", 37821), Tuple.Create("Content/Templates/Ace/assets/js/ace/ace.onpage-help.js", 37821), true)
);

WriteLiteral("></script>\r\n\r\n\r\n");

WriteLiteral("    ");

            
            #line 711 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.Partial("_PartialView/Gritter"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 713 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
