#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Pesquisa/Index.cshtml")]
    public partial class _Views_Pesquisa_Index_cshtml : System.Web.Mvc.WebViewPage<Dictionary<string, KeyValuePair<string, string>>>
    {
        public _Views_Pesquisa_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Pesquisa\Index.cshtml"
  
    ViewBag.Title = "Pesquisa";
    ViewBag.Description = Model != null && Model.Count() > 0 ? "Resultados para '" + ViewBag.Pesquisa + "'" : "Ops! Não encontramos resultados para '" + ViewBag.Pesquisa + "'";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Pesquisa\Index.cshtml"
 if (Model != null && Model.Count() > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <ul");

WriteLiteral(" style=\"list-style:none;\"");

WriteLiteral(">\r\n");

            
            #line 9 "..\..\Views\Pesquisa\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Pesquisa\Index.cshtml"
         foreach (var x in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 419), Tuple.Create("\"", 440)
            
            #line 11 "..\..\Views\Pesquisa\Index.cshtml"
, Tuple.Create(Tuple.Create("", 426), Tuple.Create<System.Object, System.Int32>(x.Value.Value
            
            #line default
            #line hidden
, 426), false)
);

WriteLiteral("><i");

WriteAttribute("class", Tuple.Create(" class=\"", 444), Tuple.Create("\"", 464)
            
            #line 11 "..\..\Views\Pesquisa\Index.cshtml"
, Tuple.Create(Tuple.Create("", 452), Tuple.Create<System.Object, System.Int32>(x.Value.Key
            
            #line default
            #line hidden
, 452), false)
);

WriteLiteral("></i> ");

            
            #line 11 "..\..\Views\Pesquisa\Index.cshtml"
                                                                 Write(x.Key);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 12 "..\..\Views\Pesquisa\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n");

            
            #line 14 "..\..\Views\Pesquisa\Index.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <h1></h1>\r\n");

WriteLiteral("    <h3>Algumas dicas para encontrar o que precisa:</h3>\r\n");

WriteLiteral(@"    <ol>
        <li>Use verbos das ações desejadas. Por ex.: <b>Visualizar</b>, <b>Ver</b>, <b>Cadastrar</b> e etc...</li>
        <li>Junte os verbos com o recurso desejado. Por ex.: 'Visualizar <b>nota</b>, Cadastrar <b>local</b>, Editar <b>pessoa</b>'</li>
    </ol>
");

            
            #line 23 "..\..\Views\Pesquisa\Index.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
