#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Noticia.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_PartialView/Noticias.cshtml")]
    public partial class _Views_Shared__PartialView_Noticias_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<LVSA.Noticia.Application.ViewModels.NoticiaViewModel>>
    {
        public _Views_Shared__PartialView_Noticias_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
  
    string serverCDN = System.Web.Configuration.WebConfigurationManager.AppSettings["Address_LVSA.CDN.Presentation"];

    LVSA.Security.Application.Models.Seguranca Seguranca = ((LVSA.Security.Application.Models.Seguranca)TempData["Seguranca"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
 if (Model != null)
{


            
            #line default
            #line hidden
WriteLiteral("    <li");

WriteLiteral(" class=\"transparent\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n            <i");

WriteAttribute("class", Tuple.Create(" class=\"", 472), Tuple.Create("\"", 617)
, Tuple.Create(Tuple.Create("", 480), Tuple.Create("ace-icon", 480), true)
, Tuple.Create(Tuple.Create(" ", 488), Tuple.Create("fa", 489), true)
, Tuple.Create(Tuple.Create(" ", 491), Tuple.Create("fa-envelope", 492), true)
            
            #line 13 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
, Tuple.Create(Tuple.Create(" ", 503), Tuple.Create<System.Object, System.Int32>(Model.Where(w => !w.UsuarioIdSet.Contains(Seguranca.Usuario.Id)).Count() > 0 ? "icon-animated-vertical" : ""
            
            #line default
            #line hidden
, 504), false)
, Tuple.Create(Tuple.Create("  ", 615), Tuple.Create("", 615), true)
);

WriteLiteral("></i>\r\n");

            
            #line 14 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
             if (Model.Where(w => !w.UsuarioIdSet.Contains(Seguranca.Usuario.Id)).Count() > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"badge badge-success\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                                              Write(Model.Where(w => !w.UsuarioIdSet.Contains(Seguranca.Usuario.Id)).Count());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 17 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </a>\r\n\r\n        <ul");

WriteLiteral(" class=\"dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown" +
"-close\"");

WriteLiteral(">\r\n");

            
            #line 21 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
             if (Model.Count() > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"dropdown-header\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"ace-icon fa fa-envelope-o\"");

WriteLiteral("></i>\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                Write(Model.Count());

            
            #line default
            #line hidden
WriteLiteral(" notícia");

            
            #line 25 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                                        Write(Model.Count() > 1 ? "s" : "");

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n");

            
            #line 27 "..\..\Views\Shared\_PartialView\Noticias.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"dropdown-content\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-navbar\"");

WriteLiteral(">\r\n\r\n");

            
            #line 31 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                         foreach (var x in Model.OrderByDescending(o => o.PublicadoEm).Take(5))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1571), Tuple.Create("\"", 1633)
            
            #line 34 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
, Tuple.Create(Tuple.Create("", 1578), Tuple.Create<System.Object, System.Int32>(Url.Action("Visualizar", "Noticia", new { id = x.Id })
            
            #line default
            #line hidden
, 1578), false)
);

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n");

            
            #line 35 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                                     if (x.ImagemSet == null || x.ImagemSet.Count() == 0)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1828), Tuple.Create("\"", 1880)
            
            #line 37 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
, Tuple.Create(Tuple.Create("", 1834), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 1834), false)
, Tuple.Create(Tuple.Create("", 1846), Tuple.Create("Content/Images/logo_ubec_cinza.png", 1846), true)
);

WriteLiteral(" class=\"msg-photo\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 1899), Tuple.Create("\"", 1913)
            
            #line 37 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                                         , Tuple.Create(Tuple.Create("", 1905), Tuple.Create<System.Object, System.Int32>(x.Autor
            
            #line default
            #line hidden
, 1905), false)
);

WriteLiteral(" />\r\n");

            
            #line 38 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2083), Tuple.Create("\"", 2164)
, Tuple.Create(Tuple.Create("", 2089), Tuple.Create("data:image;base64,", 2089), true)
            
            #line 41 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
, Tuple.Create(Tuple.Create("", 2107), Tuple.Create<System.Object, System.Int32>(System.Convert.ToBase64String(x.ImagemSet.First().Valor)
            
            #line default
            #line hidden
, 2107), false)
);

WriteLiteral(" style=\"width:45px;height:45px;\"");

WriteLiteral(" class=\"msg-photo\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 2215), Tuple.Create("\"", 2229)
            
            #line 41 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                                                                                                      , Tuple.Create(Tuple.Create("", 2221), Tuple.Create<System.Object, System.Int32>(x.Autor
            
            #line default
            #line hidden
, 2221), false)
);

WriteLiteral(" />\r\n");

            
            #line 42 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <span");

WriteLiteral(" class=\"msg-body\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"msg-title\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"blue\"");

WriteLiteral(">");

            
            #line 45 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                                                          Write(x.Autor);

            
            #line default
            #line hidden
WriteLiteral(":</span>\r\n                                            <b>");

            
            #line 46 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                                           Write(x.Titulo.Length > 55 ? x.Titulo.Substring(0, 55) + "..." : x.Titulo);

            
            #line default
            #line hidden
WriteLiteral("</b>\r\n                                        </span>\r\n\r\n                        " +
"                <span");

WriteLiteral(" class=\"msg-time\"");

WriteLiteral(">\r\n                                            <span>");

            
            #line 50 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                                             Write(x.PublicadoEm);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        </span>\r\n                       " +
"             </span>\r\n                                </a>\r\n                    " +
"        </li>\r\n");

            
            #line 55 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </ul>\r\n                </li>\r\n");

            
            #line 59 "..\..\Views\Shared\_PartialView\Noticias.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"dropdown-footer\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3110), Tuple.Create("\"", 3146)
            
            #line 61 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
, Tuple.Create(Tuple.Create("", 3117), Tuple.Create<System.Object, System.Int32>(Url.Action("Show","Noticia")
            
            #line default
            #line hidden
, 3117), false)
);

WriteLiteral(">\r\n                        Ver todas notícias\r\n                    </a>\r\n        " +
"        </li>\r\n");

            
            #line 65 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"dropdown-footer\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(">\r\n                        Ops! Ainda não há notícias\r\n                    </a>\r\n" +
"                </li>\r\n");

            
            #line 73 "..\..\Views\Shared\_PartialView\Noticias.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n    </li>\r\n");

            
            #line 77 "..\..\Views\Shared\_PartialView\Noticias.cshtml"

}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
