#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LVSA.Base.Presentation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Param/Index.cshtml")]
    public partial class _Views_Param_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<LVSA.Base.Presentation.ViewModels.ParamViewModel>>
    {
        public _Views_Param_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Param\Index.cshtml"
  
    string serverCDN = System.Web.Configuration.WebConfigurationManager.AppSettings["Address_LVSA.CDN.Presentation"];
    
    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewBag.Title = "Parâmetros para esta sessão";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<div");

WriteLiteral(" class=\"login-container\"");

WriteLiteral(">\r\n\r\n    <br /><br />\r\n\r\n    <div");

WriteLiteral(" class=\"center\"");

WriteLiteral(">\r\n        <img");

WriteLiteral(" class=\"img-responsive\"");

WriteLiteral(" style=\"width: 400px; height:auto\"");

WriteAttribute("src", Tuple.Create(" src=\"", 456), Tuple.Create("\"", 503)
            
            #line 16 "..\..\Views\Param\Index.cshtml"
, Tuple.Create(Tuple.Create("", 462), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 462), false)
, Tuple.Create(Tuple.Create("", 474), Tuple.Create("/Content/Images/logo_LVSA.png", 474), true)
);

WriteLiteral(" border=\"0\"");

WriteLiteral(">\r\n    </div>\r\n\r\n    <br />\r\n\r\n    <div");

WriteLiteral(" class=\"space-6\"");

WriteLiteral("></div>\r\n\r\n    <div");

WriteLiteral(" class=\"position-relative\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"login-box\"");

WriteLiteral(" class=\"login-box visible widget-box no-border\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"widget-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"widget-main\"");

WriteLiteral(">\r\n                    <h4");

WriteLiteral(" class=\"header lighter bigger\"");

WriteLiteral(" style=\"color: #3E3C54;\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"ace-icon fa fa-cogs\"");

WriteLiteral("></i>\r\n                        parâmetros para esta sessão\r\n                    <" +
"/h4>\r\n\r\n                    <div");

WriteLiteral(" class=\"space-6\"");

WriteLiteral("></div>\r\n\r\n");

            
            #line 34 "..\..\Views\Param\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Param\Index.cshtml"
                     using (Html.BeginForm("Index", "Param", FormMethod.Post, new { @id = "Parametros" }))
                    {
                        if (Model != null)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <fieldset>\r\n\r\n");

WriteLiteral("                                ");

            
            #line 40 "..\..\Views\Param\Index.cshtml"
                           Write(Html.EditorFor(model => model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                <div");

WriteLiteral(" class=\"space\"");

WriteLiteral("></div>\r\n\r\n                                <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" name=\"Selecionar\"");

WriteLiteral(" class=\"width-100 pull-right btn btn-sm btn-primary\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral("></i>\r\n                                        <span");

WriteLiteral(" class=\"bigger-110\"");

WriteLiteral("> Selecionar</span>\r\n                                    </button>\r\n             " +
"                   </div>\r\n\r\n                                <div");

WriteLiteral(" class=\"space-6\"");

WriteLiteral("></div>\r\n\r\n                                <div");

WriteLiteral(" class=\"social-or-login center\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"bigger-110\"");

WriteLiteral("></span>\r\n                                </div>\r\n\r\n                            <" +
"/fieldset>\r\n");

            
            #line 58 "..\..\Views\Param\Index.cshtml"

                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                </div><!-- /.widget-main -->\r\n\r\n \r\n            </div><!-- /.w" +
"idget-body -->\r\n        </div><!-- /.login-box -->\r\n\r\n\r\n    </div><!-- /.positio" +
"n-relative -->\r\n\r\n</div>\r\n\r\n<div");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"white\"");

WriteLiteral(">© ");

            
            #line 75 "..\..\Views\Param\Index.cshtml"
                     Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" – UBEC – União Brasiliense de Educação e Cultura</span>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"navbar-fixed-top align-right\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n        <br />\r\n        &nbsp;\r\n        <a");

WriteLiteral(" class=\"white\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2656), Tuple.Create("\"", 2694)
            
            #line 82 "..\..\Views\Param\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2663), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Contexto")
            
            #line default
            #line hidden
, 2663), false)
);

WriteLiteral(">alterar contexto</a>\r\n        &nbsp;\r\n        <a");

WriteLiteral(" class=\"white\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2758), Tuple.Create("\"", 2794)
            
            #line 84 "..\..\Views\Param\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2765), Tuple.Create<System.Object, System.Int32>(Url.Action("Logout","Login")
            
            #line default
            #line hidden
, 2765), false)
);

WriteLiteral(">sair</a>\r\n        &nbsp;\r\n        &nbsp;\r\n    </div>\r\n</div>\r\n\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2892), Tuple.Create("\"", 2967)
            
            #line 92 "..\..\Views\Param\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2898), Tuple.Create<System.Object, System.Int32>(serverCDN
            
            #line default
            #line hidden
, 2898), false)
, Tuple.Create(Tuple.Create("", 2910), Tuple.Create("Content/Templates/Ace/assets/js/ace/elements.typeahead.js", 2910), true)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n\r\n            $(\'select\').change(function () {\r\n     " +
"           $(\'#Parametros\').submit();\r\n            });\r\n\r\n        });\r\n    </scr" +
"ipt>\r\n");

});

        }
    }
}
#pragma warning restore 1591
